### ISSUE TITLE
Server log analysis in response to data breach cases

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1017]
As mentioned in the High Risk Case and Policy call on 2022-02-24

>Should we clarify when do detailed log analysis in major data breach cases

> This could involve work on tools to make reporting easier. 

> Create a Standardise response in these cases

**Comment by garethrees** [comment]
I think there are 3 key elements to making progress here, which I’ve detailed further below.

* Having a shared view of what we’ll even consider above the “threshold” (https://github.com/mysociety/whatdotheyknow-theme/issues/1378)
* Tools that make it quicker to produce a report so that it’s a 3-6 minute task instead of 30-60. (https://github.com/mysociety/whatdotheyknow-theme/issues/1379)
* A better process for raising these requests to someone who can handle them. (https://github.com/mysociety/whatdotheyknow-theme/issues/1380)

For us to be able to change the default stance all 3 need to be in place, and even then I think we still ought to consider this a “best effort” service.
