### ISSUE TITLE
Put reviews of WhatDoTheyKnow press coverage on the public rather than internal blog

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1029]
This could be a shift in terms of where resources are directed. 

This also could be automated via:

* https://github.com/mysociety/alaveteli/issues/6701

and could be further improved if some of the ideas in the comments at 

https://github.com/mysociety/alaveteli/issues/5483

were implemented.

**Comment by garethrees** [comment]
I think this is one for @MyfanwyNixon to comment on. While I agree with the general improvements around tracking links to requests via Alaveteli itself, the current press mentions encompass more than just request <-> article links. They might note WDTK in general, so I think we'd still want to consider how we do this more generally.

Though I don't object to them being public, I don't know that our blog readers would care much about these posts.

**Comment by MyfanwyNixon** [comment]
One option might be a static page that gets automatically compiled, rather than blog posts - I guess that's what [#6701](https://github.com/mysociety/alaveteli/issues/6701) is.

The problem I see with blog posts is that to make them interesting they require some editorial input, and I don't always have time for that. Could be a job for a volunteer though, to check [the spreadsheet ](https://docs.google.com/spreadsheets/d/1s4oDv57aKHL_yuk46eWPMx63sapzdJ-HN78ly2we7Fs/edit#gid=648337460) say monthly, and create a post around the latest links?

**Comment by garethrees** [comment]
> One option might be a static page that gets automatically compiled, rather than blog posts - I guess that's what https://github.com/mysociety/alaveteli/issues/6701 is.

Yeah, though this is only about other sources referencing specific requests made on WDTK, not, for example, a piece that mentions WhatDoTheyKnow more generally. I don't think it would be a replacement for your organisation-wide view of all mentions.

**Comment by HelenWDTK** [comment]
Closing as unplanned
