### ISSUE TITLE
Develop and share a "volunteer plan"

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1038]
This is probably an overarching ticket covering things like:

* The volunteering strategy ... the scope of potential volunteer roles 
* Volunteer recruitment and retention
* Community building - engaging a wider group of ~volunteers, activists, journalists etc. beyond the core admin team
* Giving opportunities for people to help out in a casual manner eg. via https://www.whatdotheyknow.com/categorise/play and https://github.com/mysociety/alaveteli/issues/229 
* Improving our documentation and ways of working to better support volunteers see eg. https://github.com/mysociety/alaveteli/labels/easier-admin   

I've taken the term "volunteer plan" from the "WDTK - Admin and Operations Journal". I'm not sure that's the best name/title but I've used it for consistency.

**Comment by sallytay** [comment]
To note: I have this scheduled to start for the Sprint starting on 28 March.

**Comment by sallytay** [comment]
Update:

The Volunteer recruitment plan has been initially developed here:
https://docs.google.com/document/d/1krs04gBl9feXk2Ygy0TQwNoNFal0EULqvGW1PDe_J0A/edit#

With a more detailed schedule here https://docs.google.com/spreadsheets/d/10XTb7V6LfLyoNVK_VAvT1E6HmkZhavkG-Symf0vlDEU/edit#gid=0 
(to note this is still a work in a progress)

As with all plans this may change and evolve as we work through the plan.

The plan is to start on phase one of this, in the Sprint starting today

**Comment by RichardTaylor** [comment]
Idea: Formalising longer term volunteering during a sabbatical or placement year of a degree course

The general principle could be that if we had someone committed to a year of volunteering they could be treated more akin to staff, essentially as a self-funded staff member on a fixed term contract.

I see something along these lines being offered by Oxfam - they have a "volunteer for a year" programme where if a volunteer commits to two days a week for six months, they get more in return from the organisation:

https://oxfambookspetergateyork.wordpress.com/2020/08/16/volunteer-for-a-year-2/

**Comment by sallytay** [comment]
To update on the initial phase of this plan, which was to prepare for recruitment.

Tasks completed:

- Create volunteer job descriptions
- Create a comprehensive list of volunteer web page improvements and related pages
- Make the inbox more user friendly
- Training on workable and look at how applications flow works 
- Communications plan for recruitment

Tasks started, but still to be completed
- Wiki updates for pages key for new volunteers

There is a detailed progress report that I wrote before I was off, which can be seen in full here  https://docs.google.com/document/d/1AIrEdIgGalbyD_iI3b3L91cWBVO9y4CiXSGhyDqbhM4/edit#

The schedule for the next part of this plan can be found here https://docs.google.com/spreadsheets/d/10XTb7V6LfLyoNVK_VAvT1E6HmkZhavkG-Symf0vlDEU/edit#gid=0

**Comment by sallytay** [comment]
### Conclusion of this initial recruitment plan

The scope of the initial plan was changed on 11 July 2022 to only include recruiting for one specific role of FOI database administrator, due to available resources. Some tasks related to the other roles had already been completed at this point.

I've just posted an internal blog on my experience of the recruitment https://blogs.mysociety.org/internal/2022/10/03/a-new-approach-to-recruiting-whatdotheyknow-volunteers-did-it-work

If you are interested in some stats, you can view them here https://docs.google.com/spreadsheets/d/12LrGFjFXiGOq_UKWzIlk3FRf57N7gjv_AyXQB5MNqrI/edit#gid=0

### Summary of tasks and tickets completed

**Create volunteer job descriptions for initial recruitment phase:** 
- Volunteer job descriptions and Wiki page  #1145  

**Create a comprehensive list of volunteer web page improvements and related pages**
- Volunteer webpage improvements #1178
- Create new volunteering specific contact form #1179
- Update page help/how/intro #1190
- Update volunteer credits section #1189

**Awaiting deployment**
- Update text for 'Membership of the Admin team' #1180

**Make the inbox more user friendly**
- New WDTK inbox guide - this had already been done by Helen and added to the wiki https://wdtkwiki.mysociety.org/wiki/Support_mailbox#Managing_the_shared_mailbox
- Canned responses improvements. Key tickets completed: 
>Sort the templates in the inbox  #990 
>Include standard legitimate interests in GDPR Legitimate Interest Response template #1162 (to note since completing this more improvements have been suggested to be worked on). 
>Other tickets completed  #1148,  #1151,  #977,  #1191
>Ticket still open where some work has been done  #1060 

**Workable recruitment** 
- Training on workable completed and able to use for future campaigns if we choose to use this again
- Process created and added to the wiki https://wdtkwiki.mysociety.org/wiki/Workable_process

**Communications plan**
- Created with Myf
- Job advert promoted via the on site banner, mySociety and WhatDoTheyKnow twitter accounts and mySociety newsletter and via Workable

**Wiki updates for pages key for new volunteers**
- Updates to the Wiki #1298, #1304 and #1303. 
- Plus additional Wiki page created [https://wdtkwiki.mysociety.org/wiki/Tasks_for_volunteer_database_administrators] by John on tasks to complete
- The Wiki is continuing to be updated to be more user friendly in general and for our newly recruited volunteers and existing team  by Helen, John, William and Richard

**Next steps**
- Recruiting new volunteers and retaining our current volunteers is an ongoing task. To follow on from this plan:
- Seek feedback from new volunteers to improve future recruitment plans
- In 2023 work to create another plan for volunteer recruitment, learning lessons from this plan and  using information from the annual inbox audit and Github tickets to identify the gaps in resources.
- In the meantime potential volunteers can contact us using the new contact form.
- Consider other ideas for recruiting volunteers such as #1194

**Out of scope for this project but identified as needing work**
- Volunteer agreement improvements #864
- Agree and publish a statement on volunteering principles #1104 linked to #1187 (work on this needs scheduling)
- A new webpage for Donations to separate from volunteering page (needs a bit of shaping before ticketing] (work on this needs scheduling)
