### ISSUE TITLE
Decide if to release process document when responding to relevant Subject Access Requests

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#1049]
In recent cases we have released (redacted versions)

* Account user profile information, including links to requests and annotations 
* Details of censor rules applied to the user account (if any)
* Email correspondence identified by a search of the data subjects name and email email address as provided by them
* A copy of our process document 

Depending the on the material that we hold on the data subject, this of course may vary.

We have a questions over the release of our process document - this is effectively our checklist to make sure that we have collected all the relevant data, the material has been redacted where needed and then reviewed by another admin before release.

As this is a relatively new document there has been some inconsistency in whether we should release this or not. We have previously released it for these reasons:
 
> Because the document does contain the user's data in the current form - releasing it does have the benefit of demonstrating transparent administration,

I think this is a good approach. 

However it would be good for us all to agree on this so that we can make this a clear policy for what material we release.

**Comment by RichardTaylor** [comment]
Argument made on the high risk cases call:

* This is information about our process, it isn't information about the individual. 

Argument for not releasing the process document

* The process document is created after the subject access request has come in; it wasn't held as of the date of the request. 

Argument for releasing the document:

* We try to release everything we hold at the time of responding so that if we get further requests, or a "meta request" (a request seeking information about how we dealt with the initial request) we have nothing further to release.

**Comment by RichardTaylor** [comment]
>Depending the on the material that we hold on the data subject, this of course may vary.

Another big source of variation is requests themselves, many subject access requests are specific about the information they relate to.

**Comment by HelenWDTK** [comment]
Closing as completed via subsequent review of SAR handling
