### ISSUE TITLE
Reinstate #anonymous anchor and question in privacy help page

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#1058]
It looks like in commit https://github.com/mysociety/whatdotheyknow-theme/commit/c796a40d8d643d528cb91663390ed69ca00a0f3f we got shot of the question "Why are there anonymous requests on the site?" and the #anonymous anchor, which is used in a link when there is an external request.

It's not clear whether this removal was intentional.

I propose reinstating the question and anchor

**Comment by mdeuk** [comment]
I'm guessing the part relevant here might well be:
` Sometimes, for various reasons including proven endangerment to the individual, we will remove a user’s name from the site; when we do so we make this clear; typically by replacing the name with “[name removed]”.`

… if so, I'd gladly support a variant of this being reinstated - it's clearly relevant to our current practices.

**Comment by garethrees** [comment]
It's slightly different actually. For some period we ran a [commercial service](https://www.mysociety.org/2014/02/10/brighton-and-hove-city-council-launch-new-foi-system-in-aim-to-become-more-transparent/) that kinda integrated with WDTK as a disclosure log.

[Here's an example request](https://www.whatdotheyknow.com/request/looked_after_children_stats_5). I'd actually like to [remove this functionality](https://github.com/mysociety/alaveteli/issues/6446#issuecomment-930022324) entirely from Alaveteli because it was only used for ~2-3 years by one council in the UK. Tricky thing is what to do about the ~2000 "external requests" we have.

Either way, I'm -1 on reinstating this given it accounts for an insignificant number of requests and the direction is to make this "go away" in one way or another.

**Comment by mdeuk** [comment]
> Either way, I'm -1 on reinstating this given it accounts for an insignificant number of requests and the direction is to make this "go away" in one way or another.

My assumption was that we would be recycling the part about the appearance of [name removed], rather than reinstating the reference to FoI Register - that’s been gone too long now I’d say.

We could, in theory just take the opportunity to review the text se have for mobile / email address auto removals and add a reference there, rather than going into detail. Many of these cases will be because of an RtE, but not all - so some generic boilerplate might be best.

**Comment by MattK1234** [comment]
Given we have updated and annotated all of the external requests as part of removing the feature, closing this.
