### ISSUE TITLE
Update statistics on rate of success of internal reviews

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1068]
https://www.whatdotheyknow.com/help/unhappy#internal_review

Current:

>There's a good chance an internal review will prompt a change in the public body's stance. [For requests made to central government, 22% of internal reviews resulted in some change to the original decision and 9% were completely overturned](https://research.mysociety.org/sites/foi/reviews/), 

Proposed

>There's a good chance an internal review will prompt a change in the public body's stance. [Based on Scottish data, 40% of internal reviews result in some form of new information being released, and based on UK central government data roughly 25% of internal reviews lead to more information being released](https://research.mysociety.org/html/reforming-foi/l/7.62.cqnd7.zdv8i.6njs-.y6jyl.html), 

Could rewrite that so there's not so much link text. 

Getting @ajparsons's work onto the help pages and to our users!

**Comment by garethrees** [comment]
+1, great to see research integrated into front-line services.

I think I'd link "NN% of internal reviews" in each case. Don't think it matters that they link to the same paragraph.

**Comment by ajparsons** [comment]
Glad to see paragraph level links being used!

**Comment by ajparsons** [comment]
Sorry, I changed my interpretation of the Scottish stat to 16% for the new report (that's based on 'substituted decision' in [this table](https://research.mysociety.org/sites/foi-monitor/foisa/body/all-authorities/alltime/#foisa_reviews) rather than just the reverse of 'wholly/partially upheld' (which also includes late responses etc). 

I'm going to update the original report, and will do a PR for this page.

**Comment by ajparsons** [comment]
Updated paragraph with edit notes at bottom: https://research.mysociety.org/html/reforming-foi/index.html#improving-the-operation-of-foi-and-eir-across-the-uk
