### ISSUE TITLE
Review House of Commons Disqualification Act 1975 for mentions of bodies we might want to list

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1071]
The schedules to the House of Commons Disqualification Act 1975 mention directly, or mention officer holders of, various bodies, some of which we might want to consider listing on WhatDoTheyKnow if we don't list them already. 

https://www.legislation.gov.uk/ukpga/1975/24/contents

**Comment by confirmordeny** [comment]
I have copied the lists of authorities in the Act here: http://foiwiki.com/foiwiki/index.php/Offices_referenced_in_the_House_of_Commons_Disqualification_Act_1975

**Comment by RichardTaylor** [comment]
Should we list the Crown Steward and Bailiff of the Manor of Northstead or the Manor of Northstead?

https://en.wikipedia.org/wiki/Manor_of_Northstead
https://en.wikipedia.org/wiki/List_of_stewards_of_the_Chiltern_Hundreds

I think not as there doesn't appear to be an extant body involved in either and there's no sign the Crown Steward and Bailiff is a corporation sole. 

I did consider adding the offices, and updating the contact details as new MPs get appointed to them (MPs email addresses keep working for a period after they cease to be MPs). I think this would be a lot of effort for almost no gain. 

The use of such obscure manoeuvrers rather than simply allowing people to resign as MPs is a transparency issue though.  Obscure is the opposite of transparent.

The situation appears worrying constitutionally as the chancellor could appoint any MPs they didn't like to these offices, removing them from their seats. [The appointments appear not to have to be accepted to take effect](https://en.wikipedia.org/wiki/Manor_of_Northstead#Appointment_of_Gerry_Adams).

**Comment by confirmordeny** [comment]
Section 8 of the Act helps to address the concern that the chancellor could appoint any MPs they didn't like to these offices:

8 Relaxation of obligation to accept office.
(1) No person being a member of the House of Commons, or for the time being nominated as a candidate for election to that House, shall be required to accept any office or place by virtue of which he would be disqualified by this Act for membership of that House, or for membership of that House for the constituency for which he is sitting or is a candidate.
(2) This section does not affect any obligation to serve in the armed forces of the Crown, whether imposed by an enactment or otherwise.

https://www.legislation.gov.uk/ukpga/1975/24/section/8

> 
> The situation appears worrying constitutionally as the chancellor could appoint any MPs they didn't like to these offices, removing them from their seats. [The appointments appear not to have to be accepted to take effect](https://en.wikipedia.org/wiki/Manor_of_Northstead#Appointment_of_Gerry_Adams).

**Comment by confirmordeny** [comment]
I agree though that the whole procedure is confusing and therefore not as transparent as it should be.

**Comment by HelenWDTK** [comment]
https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
