### ISSUE TITLE
Enable and encourage WhatDoTheyKnow specific donations

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1093]
WhatDoTheyKnow currently carries a general mySociety donate button (which is given low prominence in the footer). 

This ticket it for enabling and encouraging people to donate specifically to WhatDoTheyKnow (which might, for some, be a more attractive prospect). 

Closely linked:

 Show more information on costs and funding #434

**Comment by mdeuk** [comment]
This seems like a common-sense idea. The mySoc donations page currently notes:

> How will you use my money?
>
>When you donate to mySociety, the money will be allocated to general funds which allows us to focus on where the need is greatest and respond immediately to changing priorities.

… but doesn't give any immediate option to say "stop! I want to make a  donation into a _restricted fund_ pot". **Perhaps there's a good reason for this** - is it an accountancy nightmare?

To clarify, the Charity Commission [states](https://www.gov.uk/government/publications/charities-and-fundraising-cc20/charities-and-fundraising#technical-terms-used-in-this-guidance) that restricted funds are:

> ‘Restricted funds’ are funds subject to specific trusts that fall within the wider purposes of the charity. Restricted funds may be restricted income funds, which may be spent at the discretion of the trustees in furtherance of some particular aspect of the purposes of the charity, or they may be endowment funds where the assets must be invested or retained for actual use rather than spent.

**Comment by FOIMonkey** [comment]
AFAIUI restricted funds can create problems if a charity is unable find a way to sensibly allocate the money that is in line with its objectives/strategy. If the restriction is too narrow, funds sometimes have to be returned to donors. The other issue is that the dull things that enable the service to keep running still need to be paid for eg audit fees, insurance etc and it can be very hard to use restricted funds on these.

As with any charity, you can currently place a restriction on any donations you make by contacting mySociety. There certainly used to be a way to add a message as part of the donation process which you could also use to do this (might have been via PayPal).

**Comment by garethrees** [comment]
This one's a hard no, I'm afraid.

Unrestricted funding is like gold dust, and adding further restrictions is actually _damaging_ to our ability to run the service rather than enabling something we’re not already doing.

The roles funded by core (unrestricted) funding – our fundraiser, sysadmin, HR, etc – are critical for the programme teams being able to operate, and covers the time required of the programme team in handling things related to the project that aren't project-funded. For example, we're currently undergoing an organisation-wide infrastructure migration. This isn't really WDTK specific, and parts of the technical team have been contributing to some of this in a non-project specific way.

It's also an accounting nightmare, so in addition to the above, we'd spend even more time administering lots of small donations which would immediately significantly reduce the value of those donations.

**Comment by RichardTaylor** [comment]
This might be a proposal to develop take to the trustees, and suggest it is considered at what I think from references to it is a  trustee-staff fundraising committee.

**Comment by RichardTaylor** [comment]
A crowdfunder mySociety ran for TheyWorkForYou suggested that the funds raised would be spent on TheyWorkForYou. 

https://www.crowdfunder.co.uk/p/theyworkforyou

>On 20th December 2019 we successfully raised £17,475 with 622 supporters in 28 days

**Comment by garethrees** [comment]
> > Unrestricted funding is like gold dust, and adding further restrictions is actually damaging to our ability to run the service rather than enabling something we’re not already doing.
> I don't think this makes sense if enabling and encouraging restricted donations resulted in additional, new, donations. This ticket is about encouraging and enabling more donations, not restricting what can be done with existing donations.

Restricted donations have an increased administration complexity (and therefore cost). Since those donations are restricted to the service, the admin cost then has to come from core funding. A high number of smaller restricted donations (vs a single large restricted donation) has an exponential complexity cost.

> WhatDoTheyKnow specific donations might assist with… This isn't the kind of activity which mySociety has funded to-date.

It's also likely that promoting restricted donations via WDTK would cannibalise the currently unrestricted donations we get from WDTK, rather than provide an _extra_ source of donation revenue. If we can't fund the support infrastructure that keeps WDTK running because we've significantly reduced the unrestricted funding we get, then we’d be in a _worse_ position to be able to do interesting work like this.

**Comment by RichardTaylor** [comment]
> Since those donations are restricted to the service

As long as we were transparent that donations to the service may be used to fund the core services which mySociety provide to keep WhatDoTheyKnow running. 

>It's also likely that promoting restricted donations via WDTK would cannibalise the currently unrestricted donations

That's perhaps a hypothesis which could be tested.

**Comment by RichardTaylor** [comment]
Would need great care over charity law in respect of restricted donations.
