### ISSUE TITLE
Agree, document, and make consistent, use of tags to identify requests and bodies where responses are provided via links 

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1143]
On Tue, 12 Apr, 14:28 in an email to volunteers@ in a thread with the subject: "FOI Response sent as time-limited SharePoint Links" I proposed establishing two tags for cases where bodies have responded with a link to material being released rather than attaching it:

response_via_link  (for request threads)
responding_via_link (for bodies)

I documented this at 

https://wdtkwiki.mysociety.org/wiki/Request_tags
and
https://wdtkwiki.mysociety.org/wiki/Policies#Campaigning_Tags_Poor_Public_Body_Performance

On Wed, 13 Apr at 08:50 an alternative proposal was circulated on a volunteers@ thread with the subject: "On-site campaigning on poor auto-responders and off-site responses"

proposing responds_with_link for the body tag in this situation.

I'm all for avoiding unnecessary Latin but I thought via had been sufficiently assimilated into English.

**Comment by garethrees** [comment]
> On Tue, 12 Apr, 14:28 

Before that there were other proposals made on the [2022-03-29 Community & Activism call](https://docs.google.com/document/d/1E4-O6j2HP42yBVjRGGuTcu8GsAdy8fL1Jog1gShqI4E/edit#bookmark=id.ysltqmz4t4zi)

I've made a [short document](https://docs.google.com/document/d/1u5zVCHTSMOzBFEOQiyulTJsuGJBHJfWRp35NDYd5roc/edit) containing a table of situations and what tags have been proposed/applied.

We still have a tag missing (as far as I can tell), and a bit of duplication / inconsistency.

Let's hash it out there via comments.

**Comment by RichardTaylor** [comment]
>Before that...
And before that we'd have been already using some tags I suspect... 

>I've made a [short document](https://docs.google.com/document/d/1u5zVCHTSMOzBFEOQiyulTJsuGJBHJfWRp35NDYd5roc/edit) containing a table of situations and what tags have been proposed/applied.

I've contributed there. 

Let's get agree a set of tags ASAP, then move back to documenting them on the wiki so we're not maintaining two lists. 

(The wiki documentation is scrappy at the moment and can be improved).

**Comment by sallytay** [comment]
The table of proposed tags looks great, I've added some comments. 

I definitely agree we should have them listed on Wiki as well.

Sally

**Comment by garethrees** [comment]
Yes, the intention of the document is just to lay out the tags related to our current focus, get them aligned with google's better collaboration features, so that we can then work them back in to our normal static documentation.

**Comment by WilliamWDTK** [comment]
>     * [ ]  Add table to wiki

I think I might have a go at doing this now.  I assume I don't transfer across the striked-through ones?

**Comment by WilliamWDTK** [comment]
> *  Re-tag any bodies with crossed-out tags with the new version

It should be done for the following tags, but might want to wait until search re-indexes to check.  I also checked for requests for each tag.

- `responds_with_link`
- `response_with_link`
- `response_via_link`
- `misleading_auto_response`
- `points_to_web_form`
- `refuses_email_correspondence`
- `contact_form_only`
- `wrongly_claims_foi_no`
- `foi_refuse`
- `Offsite_response`
- `offsite_response`

**Comment by garethrees** [comment]
I've just checked through all the crossed out tags in the document. There was [one body](https://www.whatdotheyknow.com/body/midlothian_council) with the old `points_to_web_form` tag, but it looks like they're now responding nicely, so I've removed it. We now have no "old" tags, so I think we can call this closed.

**Comment by garethrees** [comment]
Dropping some screenshots of what we ended up with for others looking for inspiration on what we did.

First we used Google Docs to find existing tags and use the comment/suggestion functionality to discuss each particular tag. As we were considering both body and request tags we decided to try to find a tag that works across both contexts.

<img width="860" alt="Screenshot 2022-06-14 at 10 08 28" src="https://user-images.githubusercontent.com/282788/173539890-d9c7b929-607a-4aea-a576-578ede44e495.png">

Once we'd all agreed on the tags, we added the table to our wiki, with nice links to the search terms for each tag so that it's easy to look up which bodies or requests are tagged with any given tag. We then cleaned up any "old" tags (strikethrough in the Google Doc) with the new version.

<img width="1005" alt="Screenshot 2022-06-14 at 10 04 44" src="https://user-images.githubusercontent.com/282788/173539078-d956ad12-929a-4e5f-afb7-5ce335c47f7e.png">
