### ISSUE TITLE
Submit talk to State of the Map 2022

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1144]
The State of the Map (SotM) conference is the annual OpenStreetMap (OSM) conference run by the OpenStreetMap Foundation (OSMF). It is organised by the SotM Working Group, a team of volunteers. This year, SotM 2022 will be a hybrid event, held in person in Firenze, Italy and online! – https://2022.stateofthemap.org/calls/general

We could make a lightening talk (5 mins) about the mapping data that can be found from FOI (and WDTK in particular). We could collaboratively create the presentation, then someone could record themselves talking over the slides.
 @FOIMonkey shared some great examples:

> People use WDTK to get data for OpenStreetMap all the time - I have classified a lot of requests about the location of traffic islands!
>
> Kent CC have released the shapefiles for all the public rights of way in the county: https://www.whatdotheyknow.com/request/public_rights_of_way_data_4#incoming-2023061
>
> Recent example: https://www.whatdotheyknow.com/request/footway_gis#incoming-2008883
>
> Bins: https://www.whatdotheyknow.com/request/litter_bin_locations_and_schedul#incoming-1950784
>
> National parks: https://www.whatdotheyknow.com/request/request_for_land_owned_3#incoming-2020089
>
> Streetlights: https://www.whatdotheyknow.com/request/street_light_location_data_22#incoming-1751434
>
>  Zebra crossings, pedestrian crossings/traffic islands: https://www.whatdotheyknow.com/user/john_kariuki
>
> There are lots. There was a period of time where we had a multiple people ask for cross-section depth data of the Leeds-Liverpool canal. I've no idea why: https://www.whatdotheyknow.com/request/leeds_and_liverpool_canal_depth#incoming-1137447
>
> There was [a user](https://www.whatdotheyknow.com/user/evan_howle) asking for the location of drop kerbs because they wanted to make an app to help plot accessible routes for wheelchair users. I don't think they got much info released.
>

The messaging around submissions for lightening talks is pretty unclear:

> **Submission Types**
>
> …
>
> **Other**
>
> Your submission does not fit into any of these submission types? Please get in touch with the program committee via email (email redacted) before the end of the call for participation.
>
>
> **Other session types**
>
> We plan to provide space for other session types which cannot be submitted in advance. Details will be announced before the conference.
>
> **Lightning Talk**
>
> Lightning talks will be short 5 minute talks. There will be some spaces for last-minute in-person talks as well as spaces for pre-recorded videos. This will be announced separately.
>
> …
>
> **Timeline and Deadlines**
>
> * 25 April 2022 23:59:59 UTC: Deadline talk, workshop and panel submissions
> * 10 May 2022: Deadline [academic talk submissions](https://2022.stateofthemap.org/calls/academic)
> * End of May 2022: End of review phase, speakers will be informed
> * June 2022: Talk video production (test video and final video)
> * **August 2022: Lightning talk video production** (em mine)
> * 19-21 August 2022: State of the Map

The linked submission form doesn't have a "Lightening talk" option, so I'm guessing this is something we'll need to keep an eye on for more details. Even if we put the talk together and don't get selected, it would be a good exercise in putting one of these together for future conferences, and the material could easily be repurposed for the blog and social media channels.

**Comment by WilliamWDTK** [comment]
And it would presumably have to be a lightning talk, since the next one up is ~20 minutes + Q&A, plus the deadline is probably too close.

**Comment by RichardTaylor** [comment]
There are maps showing the location oil fields in the South of England (and an oil well location) in the document released at: 

https://www.whatdotheyknow.com/request/523935/response/1277768/attach/4/brockfdpadd%20Redacted.pdf

**Comment by RichardTaylor** [comment]
Is this an opportunity to pitch for volunteers ourselves? 

We'd love to show maps on our public body pages, and on our relevant category pages. 

Can we use data from OSM to do so? (Perhaps in some cases).

**Comment by garethrees** [comment]
> Is this an opportunity to pitch for volunteers ourselves?

I think we could sneak _something_ in about WDTK being heavily volunteer-driven.

**Comment by RichardTaylor** [comment]
Postboxes:

https://lists.openstreetmap.org/pipermail/talk-gb/2012-May/013188.html
https://postboxes.dracos.co.uk/about/

mySociety has done lots of cool stuff with maps which could get a mention

* https://www.mysociety.org/2013/04/22/fire-fire-mapumental-and-fire-engine-journey-times/
* https://www.mysociety.org/2012/08/14/mysociety-design-tips-how-we-choose-the-best-map-zoom-level/
* https://mapit.mysociety.org/

**Comment by RichardTaylor** [comment]
There is a WhatDoTheyKnow user who makes requests which look related to their Open Street Map contributions 

https://www.whatdotheyknow.com/user/robert_whittaker

They have current requests relating to mapping, and [they've made 43,221 Open Street Map edits](https://www.openstreetmap.org/user/Robert%20Whittaker). 

They also have a record of not only publicly obtaining information for use on OSM via WhatDoTheyKnow, but ensuring it is available under an appropriate licence, or rejecting an refusal on the grounds information is reasonably accessible, as it isn't reasonably accessible without agreeing to unacceptable licence terms eg. 

https://www.whatdotheyknow.com/request/official_street_names#outgoing-1276235 (from March 2022)

and

>under the Re-Use of Public Sector Information Regulations, I would like to request permission to re-use the information above under the Open Government Licence v3. The purposes for which the information is to be re-used are: (a) to help improve the mapping of Rights of Way in OpenStreetMap, and (b) to convert the datasets to a more convenient format, and then make them available for others to re-use under an open licence.

https://www.whatdotheyknow.com/request/public_rights_of_way_gis_data_11#outgoing-1161176

**Comment by RichardTaylor** [comment]
As this is an international conference we should refer to the Alaveteli network and the potential for doing what we've seen done in the UK elsewhere.

**Comment by garethrees** [comment]
> As this is an international conference we should refer to the Alaveteli network and the potential for doing what we've seen done in the UK elsewhere.

Best place to do that is [the alaveteli-users group](https://groups.google.com/g/alaveteli-users).

**Comment by rjw62** [comment]
> There is a WhatDoTheyKnow user who makes requests which look related to their Open Street Map contributions
> 
> https://www.whatdotheyknow.com/user/robert_whittaker

That would be me :) Thanks for the invitation.

One good point to make I think is the following:

OSM takes a fairly strict line on copyright issues, so it's important that mappers know whether or not they can use third-party datasets, and that others can verify any use at a later date. WDTK is really useful in this regard, since it provides a public record not only of released data, but of any permissions obtained to re-use the data (e.g. under RoPSIR).

One notable success has been using FOIA and RoPSIR to obtain Public Rights of Way data. I've got a summary table at https://osm.mathmos.net/prow/open-data/ with various links to sources and licensing information. You'll see lots of WDTK links in the comments. Many different people have been using this route to submit similar requests, following early releases from (I think) Essex (pro-active) and Cambridgeshire (forced by me under FOIA and RoPSIR).

**Comment by WilliamWDTK** [comment]
> RoPSIR

Is that something we want to look into more generally on WDTK?

---

Also, I've created a [document to start working on a script/plan for the talk](https://docs.google.com/document/d/1X4wOWVptTSHjEzhcQmIfQm4yered4tRTBxOc3Qyuktg/edit?usp=sharing), which can be converted to a blog post if/when necessary.  It is accessible to anyone with a mySociety Google Account, but anyone else who wants to view or comment on it is welcome to request access, I'm sure.

**Comment by WilliamWDTK** [comment]
> > RoPSIR
> 
> Is that something we want to look into more generally on WDTK?

I believe it is, since we've received an email about it (not directly referencing it, but related), hence #1195.  So, this would be worth mentioning in any talk.

**Comment by WilliamWDTK** [comment]
A few updates on this (SotM itself, not our preparations, which I don't think have progressed particularly):

- A call for posters has been made.  Perhaps we could make a poster, rather than a lightning talk.
It should be A0 size (841×1189 mm).
It should be related to OSM (I assume it's the same requirement as any talk we might submit, but I don't know for sure).
It should be under an open licence (CC-BY-SA 3.0 or later).
It must be a PDF with a max size of 30-40 MB.
Only 20 posters will be shortlisted, we may submit up to 2.
Inspiration: [SotM 2021 Posters](https://2021.stateofthemap.org/posters/)
[Details of this year's call for posters](https://2022.stateofthemap.org/calls/posters/)
- [The programme](https://2022.stateofthemap.org/programme/) has been released.  Talks of note (they're probably all noteworthy in a general sense, these are most closely linked to what we might be interested in, even if not particularly close in reality):
[*Integrating OpenStreetMap in the local governance of Nepal*](https://2022.stateofthemap.org/sessions/FABJFJ/), [*Using OpenStreetMap in the case of the social and economic infrastructure mapping project of Togo*](https://2022.stateofthemap.org/sessions/PJBGXZ/) and [*Public Domain Map: Crowdsourcing the Future of Government Data*](https://2022.stateofthemap.org/sessions/CFVMU7/).

There still don't seem to be any details on the submission of lightning talks.

**Comment by garethrees** [comment]
I don't think we got to this before the deadline, so going to close. Still – great that we documented a bunch of map-related resources for future use 🗺️
