### ISSUE TITLE
Add snippet on caching to canned responses

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1151]
We often write something like:

>It may take some time for the changes we've made to take effect from your perspective due to caching. 

this isn't in any of the current canned responses, and it might be a candidate for a snippet.

**Comment by sallytay** [comment]
This is included in the GDRP RtE confirm anon response:

This change takes effect instantly on our systems, however it could take up to 24 hours for this to be reflected in the version of WhatDoTheyKnow that you can see yourself - this is because, like many other busy websites, we use a caching system.

We can add it as a snippet as well. But to note we do not have more space left for more templates to be stored in the inbox
as previously mentioned, anything that we add will mean something is removed,

**Comment by sallytay** [comment]
I'll add this to the work on ticket #1060

**Comment by sallytay** [comment]
I've added the snippet text for this on the canned response back up document and to the Wiki canned responses page snippet section.

The template list within the inbox is currently full so it can't be added there at the moment
