### ISSUE TITLE
Create canned response/snippet about withdrawing requests

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1191]
I think I have written a few times to users to explain how to withdraw a request, so we could create a canned response/snippet for it.

Alternatively, make it more obvious how to do it… (which would be an Alavateli issue)

**Comment by sallytay** [comment]
Proposed new canned response below:

How to withdraw a request

We do not remove requests from WhatDoTheyKnow as detailed in our policy, https://www.whatdotheyknow.com/help/how#information_removal

If you no longer wish to proceed with your request ### add in request link ###, you can mark it as withdrawn.

To withdraw a request, you need to go to the request page, making sure that you logged in.

Press the grey "Actions" button at the top of the page, then select "Update the status of this request". 

In the yellow box, select "I would like to withdraw this request" (under "Other"). This will mark your request as withdrawn.

However this does not notify the authority, we would recommend that you then send a follow-up message to the authority, letting them know that you no longer wish to proceed with the request, this can also be done by using the option in the “Actions” button and selecting “write a reply”

**Comment by garethrees** [comment]
Nice! Some tweaks:

* Remove `### add in request link ###` – adds more burden for us to remember to replace; I don't think it adds much for the user
* Condense instructions for finding "Update the status of this request" link.
  * Removed "grey" – I'd call it "dark brown" (!), and it makes it resilient against colour changes (e.g. as proposed in https://github.com/mysociety/whatdotheyknow-theme/issues/1138#issuecomment-1099064678)
  *  Signing in is more incidental (they may already be signed in), so put that on the end
* After classifying as withdrawn we automatically send the user to the followup page (see https://github.com/mysociety/alaveteli/issues/6440#issuecomment-1129886298). By this point the classification _has_ been applied though, so +1 on still emphasising that they ought to be polite. 

I think we should say _why_ they should tell the authority it's been withdrawn (saves them time, public money, whatever). I haven't thought of a phrase so that's still a todo if anyone wants to take a stab. Would be happy for it to be put in service as-is though.

---

How to withdraw a request

We do not remove requests from WhatDoTheyKnow as detailed in our policy, https://www.whatdotheyknow.com/help/how#information_removal

If you no longer wish to proceed with your request you can mark it as withdrawn.

To withdraw a request, press the "Actions" button at the top of the request page, then select "Update the status of this request". You may be asked to sign in during this part of the process.

In the yellow box, select "I would like to withdraw this request" (under "Other"). This will mark your request as withdrawn.

We recommend that you then send a follow-up message to the authority, letting them know that you no longer wish to proceed with the request.

**Comment by sallytay** [comment]
Updated draft below, I've taken out the reference to 'yellow' box for the same accessibility issues and added in the suggested final line.

How to withdraw a request

We do not remove requests from WhatDoTheyKnow as detailed in our policy, https://www.whatdotheyknow.com/help/how#information_removal

If you no longer wish to proceed with your request you can mark it as withdrawn.
To withdraw a request, press the "Actions" button at the top of the request page, then select "Update the status of this request". You may be asked to sign in during this part of the process.

You will then give some options, select "I would like to withdraw this request" (under "Other"). This will mark your request as withdrawn.

We recommend that you then send a follow-up message to the authority, letting them know that you no longer wish to proceed with the request. By doing this it helps the authority to save their time, and public money by no longer having to process your request.



To note we have run out of room in the inbox to store any new templates. I've added this to the back up document and listed it on the Wiki.

There is a ticket on the limit being reached, that is still open for possible solutions to this problem https://github.com/mysociety/whatdotheyknow-theme/issues/990
