### ISSUE TITLE
Consider use of per-message tags

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1214]
In light of

https://github.com/mysociety/alaveteli/pull/7075

* Document per-message tags
* Understand how a search for `tag:term` is impacted by a tag on a message
* Decide on our approach for using this feature, in particular in relation to campaigning / authority performance tags.  https://wdtkwiki.mysociety.org/wiki/Authority_Performance_Tags

**Comment by HelenWDTK** [comment]
We have tagged 7 incoming and 1 outgoing message so far, mainly with case refs. At the moment, tagging a message doesn't do anything, which is why we don't really use it. This should be revisited once the ability to display tag based notes on the request thread based on message tags has been implemented.
