### ISSUE TITLE
Improve, and ideally make comprehensive, our coverage of navigation authorities

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1254]
One possible source to compare our data with:

https://waterways.org.uk/waterways/uk-canal-map/who-maintains-the-uks-canals-and-rivers

**Comment by RichardTaylor** [comment]
https://www.whatdotheyknow.com/body/list/navigation_authority

**Comment by RichardTaylor** [comment]
See also

https://en.wikipedia.org/wiki/Navigation_authority

**Comment by RichardTaylor** [comment]
I've started a wiki page:

https://wdtkwiki.mysociety.org/wiki/Navigation_Authorities

**Comment by confirmordeny** [comment]
I think this is essentially complete - please see the above link on FOIWiki.

**Comment by confirmordeny** [comment]
Coverage has improved substantially in recent months. I have recently tagged some local authorities as navigation authorities and added notes. We now have 114 navigation authorities on the site. In my view, our coverage of navigation authorities is significantly better than that of Wikipedia.

This is the best list against which to check our coverage:
https://foiwiki.com/foiwiki/index.php/Navigation_authorities
There are about three left where I am not sure of the legal name and not completely sure that they still exist as navigation authorities.

I will close this now because I feel that the original ticket has been addressed. If there are further specific improvements identified then new tickets can be opened as needed.
