### ISSUE TITLE
Data licence for authorities database

### ISSUE THREAD

**Issue by ajparsons** [mysociety/whatdotheyknow-theme#1258]
WhatDoTheyKnow provides a download of all authorities:

![image](https://user-images.githubusercontent.com/8157058/176852024-806ac310-9896-4813-9cd8-3d60269f5dbd.png)

What is the licence of that dataset?

As a default, I am licencing data I release as [cc-by-4.0](https://creativecommons.org/licenses/by/4.0/), but don't want to assume.

**Comment by garethrees** [comment]
I don't think it's been thought about.

`CC BY-SA 4.0` seems more appropriate since [Alaveteli's License](https://github.com/mysociety/alaveteli/blob/develop/LICENSE.txt) requires "Modifications must be released under the same license when distributing the licensed material" (phrasing via [choosealicense](https://choosealicense.com/licenses/agpl-3.0/))
