### ISSUE TITLE
Persuade the National Archives to Archive WhatDoTheyKnow.com as part of the UK Government Web Archive

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1268]
https://www.nationalarchives.gov.uk/webarchive/

I think we may have tried this years ago, we could send them another email.

**Comment by mdeuk** [comment]
> https://www.nationalarchives.gov.uk/webarchive/
> 
> I think we may have tried this years ago, we could send them another email.

It's an interesting idea, and certainly worth further exploration. https://github.com/mysociety/alaveteli/issues/6691 did make me ponder if we could link up with Internet Archive, but a UK specific repository would also be appropriate. If not the National Archives, then perhaps a service like the [NRS Web Continuity Service](https://www.nrscotland.gov.uk/research/researching-online/web-continuity-service) (which is powered by Internet Archive) would be interested.

Incidentally - the National Archives are currently conducting a [user survey](https://www.smartsurvey.co.uk/s/UKGovernmentWebArchive/) and it would appear that they are acutely aware of the "I thought I was looking at live data" problem described in https://github.com/mysociety/alaveteli/issues/315 and  https://github.com/mysociety/alaveteli/issues/6674

![image](https://user-images.githubusercontent.com/249418/178127438-ef2058b1-5475-43a3-b7cd-5b8fafaeff85.png)

**Comment by FOIMonkey** [comment]
> I think we may have tried this years ago

We did. I think the issue was copyright. @confirmordeny wrote to them so might remember more.

**Comment by confirmordeny** [comment]
I have a vague recollection of filling in a webform to try to get the National Archives to archive the site. 

Not all the material created by public bodies is Crown Copyright so that is a complication. Public bodies often release material created by third parties in response to FOI requests. In addition, some of the information on the site is copyright of MySociety and some material is created by the site's users.

See also https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/crown-copyright/uk-crown-bodies/

**Comment by garethrees** [comment]
Related / relevant https://www.muckrock.com/news/archives/2022/jul/13/documentcloud-gateway-grants/

**Comment by HelenWDTK** [comment]
This is one for the newly formed we want to do this but can't yet label. It'd need a decent chunk of time to sort out the copyright issues/misuse issues that are too big a barrier at the present time.
