### ISSUE TITLE
Add some sort of identifier to the volunteer contact form submission email subject

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1292]
When someone makes a submission through the volunteer contact form, an email comes through to the WDTK support inbox with the subject "Message from WDTK volunteer contact form".  This means that multiple threads could end up combined, since they will have the same original sender's address etc.

I would therefore propose adding some unique identifier.  Possible identifiers:

- User ID of logged-in users (not ideal as not memorable)
- User slug of logged-in users
- Username of logged-in users
- Value of the name field for guest users
- Value of the email field for guest users

I suggest slugs and IDs rather than username to avoid rare cases where multiple users with the same name make a submission.  This could still happen with the name field for guest users, so you could use email there…

Even if the threads don't end up combined, it will make them easier to deal with.

**Comment by FOIMonkey** [comment]
+1 we had a genuine application come in over the weekend that got threaded with some form spam until I deleted it.

**Comment by mdeuk** [comment]
I've put together a PR for this (#1292) - refactoring the subject to include the user's name and a unique reference number (similar to those used on Tracker, as it fits our usual pattern).

I did consider just using a name, but this felt like it still left the risk of 'cross contamination' in threads - with no easy way in Gmail to split them apart afterward. Using a unique reference in the subject is enough to force Gmail to thread them in conversation view as different threads, rather than interlinking.

It's a bit hacky, but hopefully it does the job 😃
