### ISSUE TITLE
Help page conflicts with mySociety styleguide

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/whatdotheyknow-theme#1311]
One of our help pages contains language identified by the mySociety styleguide as being racist

 https://www.whatdotheyknow.com/help/requesting#ico_help

I'm going to attempt to fix this myself.

**Comment by RichardTaylor** [comment]
There is a volunteers@ thread with some discussion on this point. 

The styleguide may be based on an erroneous view of the phrase's etymology. 

There's some commentary at:

http://news.bbc.co.uk/1/hi/uk/1988776.stm

including:

""Its origins are elusive," ... but it is "inconceivable that it
should have been around since slave-ship days without somebody writing
it down [until the mid-20th Century].""

There's further discussion, of varying quality, elsewhere including:
https://www.phrases.org.uk/meanings/nitty-gritty.html

In 2021 the BBC did not uphold a complaint about their
political editor using the term

https://www.standard.co.uk/news/uk/bbc-laura-kuenssberg-nitty-gritty-b900886.html
https://www.bbc.co.uk/contact/sites/default/files/2021-01/4-%2017%20January%202021.pdf

I concluded on the thread:

>Personally I wouldn't use the phrase just because people might think I was being careless with language and using a phrase with racist origins, even though I think the chances are it probably doesn't have racist origins. Perhaps mySociety and WDTK following that kind of approach might be sensible. The style guide says that the phrases "come with baggage" is a reason not to use them, which might well be saying the same thing.

Another contributor agreed: 

>I tend to agree with this: once a phrase has been highlighted as potentially problematic, whether it is or not, it's just as well to avoid it.
