### ISSUE TITLE
Inside information policy

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#1354]
I think we should have a policy on inside information. I have drafted one for review and consideration by others:
https://wdtkwiki.mysociety.org/wiki/Draft_inside_information_policy

**Comment by WilliamWDTK** [comment]
To clarify for the public issue, since this is not clear from the issue as-is, this policy relates to inside information for insider trading etc.

I'm unaware of any occurences to date.  We'd want to establish our liability if an (accidental) disclosure were made through WDTK.  In many ways, this relates to general liability for releases through WDTK.

**Comment by confirmordeny** [comment]
We now have a policy: https://wdtkwiki.mysociety.org/wiki/Inside_information_policy
