### ISSUE TITLE
Add a link to CQC providers

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1364]
Where a body has a `cqc:` tag, link to it's entry online.

`<a href="https://www.cqc.org.uk/provider/«ID»">CQC provider information.</a>`

**Comment by garethrees** [comment]
For [the first one I looked at](https://www.whatdotheyknow.com/body/new_road_dental_practice_bromsgrove), interpolating the tag value (`cqc:1-211357754`) into the URL 404s: https://www.cqc.org.uk/provider/1-211357754.

The [other](https://www.whatdotheyknow.com/body/the_medical_centre_driffield_east_yorkshire) works okay: https://www.cqc.org.uk/provider/1-199694646

**Comment by garethrees** [comment]
> Is it worth it?

Ah, I see this is being worked on and improved in https://github.com/mysociety/whatdotheyknow-theme/issues/1363.

**Comment by mdeuk** [comment]
> > Is it worth it?
> 
> Ah, I see this is being worked on and improved in #1363.

I was just coming here to say that! 😃 

We're also looking at the tags for NHS bodies more generally in #1360 .

**Comment by mdeuk** [comment]
> For [the first one I looked at](https://www.whatdotheyknow.com/body/new_road_dental_practice_bromsgrove), interpolating the tag value (`cqc:1-211357754`) into the URL 404s: https://www.cqc.org.uk/provider/1-211357754.
> 
My fault - the code we've got in the tag is for the location ([1-211357754](https://www.cqc.org.uk/location/1-211357754)), rather than the provider ([1-152944110](https://www.cqc.org.uk/provider/1-152944110)).

Perhaps there's a benefit to capturing both - in which case, we could refactor to `cqclocation:` and `cqcprovider:`?

My thinking for that would be that some providers have multiple locations, and that if we are tagging it might be worth adding that data (if readily available). At a minimum, even adding the provider still enriches the metadata.

**Comment by garethrees** [comment]
Given we only have 2 I don't think it's a huge hassle to change – better to make this decision now rather than when we have 100s!

I have zero preference on any of these.

**Comment by HelenWDTK** [comment]
This issue is being closed due to a lack of discussion or resolution for over 12 months. Should we decide to revisit this issue in the future, it can be reopened.
