### ISSUE TITLE
Better coordination mechanism for log analysis requests

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1380]
We already have more work to do than we can reasonably fulfil. We are onboarding a new developer soon who may add some capacity for this type of reactive and operational work.

Usually these requests for logs are urgent, and currently it’s difficult to spot these in amongst all the other email and notifications received. It’s not clear who can handle them, and whether there are fallbacks if they can’t.

I don’t have a good suggestion for how we do better at this while maintaining simplicity yet. This may improve organically as the new developer gets onboarded.

I think we need to have a fairly strict window in which these requests remain open for whoever it is that’s handling them. For example, authorities have 72 hours to report, and then some follow up time. We could say that if we haven’t managed to produce the analysis after 5 working days, it just isn’t going to happen for this case.

**Comment by mdeuk** [comment]
My quick response to this would be:

1. Setup a Google Group for log requests - yep, I know we've got review[^1] - but this would be task specific and _only_ used for this purpose, making it easier to filter in a mailbox.
2. Slightly longer term: consider using [webhooks](https://slack.com/intl/en-gb/help/articles/115005265063-Incoming-webhooks-for-Slack) to get notifications into Slack.

We could implement both of these options using the Tracker, so that the request is structured, making it easier to know what data is being asked for, and the duration; also allowing for the relevant spaces to be setup on Google Drive automatically. Doing it this way will have the added benefit of oversight of when requests are made, and do some reporting if need be.

I should note: I don't have access on the production Slack instance to achieve (2) [^2], but it doesn't seem massively complicated to do. Also, I should note that, in terms of (1) this is a pretty quick win. 

[^1]: We don't always need logs for GDPR matters, sometimes we need them for Legal and Compliance purposes, where speed is of the essence - review is very heavy on data, so doing it all through there isn't the best.
[^2]: As per #1028, #1213, #1260

**Comment by garethrees** [comment]
All good suggestions – definitely think the stage we're at is exploring the options before we then narrow in on one and start implementing it.

Difficulty here is that it's more "cross-team" work – usually we hand these off to sysadmin. We're about to onboard a new developer who's attached to the charitable programme work but with some more sysadmin/ops focus, who might be an ideal first-responder to these. But then how do we fall back to e.g. me if we really need to. We're not very good at coordinating this type of task across the org.
