### ISSUE TITLE
Add an announcement banner about the Bank Holiday to the site

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1396]
<pre>
&lt;p&gt;Following &lt;a href="INSERT URL"&gt;the announcement about the bank holiday on 19 September 2022 for the funeral of the late Queen Elizabeth Ⅱ&lt;/a&gt;, we have updated our site. See &lt;a href="INSERT URL"&gt;this blog post&lt;/a&gt; for more information.&lt;/p&gt;
</pre>

**Comment by mdeuk** [comment]
I'm [pondering](https://github.com/mysociety/whatdotheyknow-theme/issues/1393#issuecomment-1242812444) if we might be best using a help page for the link here, as it would add permanence.

Naturally, we could link to the blog from there, but it feels like this is something that ought to be on Alaveteli itself.

If we change `blog post` to `help page`, would that work? If so, I think I'd be inclined to send this for translation at the same  time as https://github.com/mysociety/whatdotheyknow-theme/issues/1382#issuecomment-1242811607, so that we've got the request in. We can sort the text for the help page a little later on.

**Comment by WilliamWDTK** [comment]
I've no objections to that.

**Comment by sallytay** [comment]
Announcement banner can be added once https://github.com/mysociety/whatdotheyknow-theme/issues/1393 has been completed, linking to the tag

**Comment by WilliamWDTK** [comment]
We have a translation:

<pre>
Yn dilyn y cyhoeddiad am ŵyl y banc ar 19 Medi 2022 ar gyfer angladd y ddiweddar Frenhines Elizabeth Ⅱ, rydym wedi diweddaru ein gwefan. Gweler y dudalen gymorth hon am fwy o wybodaeth.
</pre>

**Comment by WilliamWDTK** [comment]
I think we probably want the `<a>` tags before `y cyhoeddiad` and after `Elizabeth II`, but maybe @FOIMonkey can advise.

**Comment by mdeuk** [comment]
> I think we probably want the `<a>` tags before `y cyhoeddiad` and after `Elizabeth II`, but maybe @FOIMonkey can advise.

I believe that's right. 👍 

If we're linking to the blog, it may be best to put a link on "the announcement" at all, and instead use the text "y dudalen gymorth" (aka "this help page") to put the link to the blog.

Naturally, we've now got the slight confusion of "help page" and "blog" (#1397) - but hey ho, it won't cause any practical issues, and I don't really want to have to get it translated again.

**Comment by WilliamWDTK** [comment]
I think this can be closed, since the funeral (and bank holiday) has happened. It can be reopened as necessary.
