### ISSUE TITLE
Blog post about not needing to mention FOI to make an FOI request

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1424]
A thing we've heard a few times recently is something along the lines of "why do people need to make an FOI request; if they just emailed the question we'd answer it".

What they suggest is an FOI request though!

Could use this to illustrate that FOI is not about being "formal", but about the ability to ask for information – whatever it may be – and expect a response.

@confirmordeny suggests "I think we could have a separate blog post called "There are no magic words"." – love this title!

**Comment by RichardTaylor** [comment]
How does this link to WhatDoTheyKnow ?

Are we interested, as WhatDoTheyKnow, in public bodies doing better at answering requests for information made via other routes?

**Comment by FOIMonkey** [comment]
> How does this link to WhatDoTheyKnow ?

People make requests using the service? We like FOI in general? 

If this makes even one person think that the "open government request" boilerplate isn't needed it'd be a win.

**Comment by RichardTaylor** [comment]
>People make requests using the service? 

But we automatically silently and invisibly insert a subject line mentioning FOI anyway. (Related ticket: https://github.com/mysociety/alaveteli/issues/5039 ) 

>If this makes even one person think that the "open government request" boilerplate isn't needed it'd be a win.

I agree that having better template letter, or making clear nothing complex is required, is needed to make it easier for more people to make requests.  (Related ticket https://github.com/mysociety/alaveteli/issues/6164 )

>We like FOI in general?

Perhaps, but we particularly like FOI requests made in public using WhatDoTheyKnow over any other route for making FOI requests. (We reluctantly support some use of embargoed requests if that's the only way we can get them to eventually appear in public, and we hope to encourage the unembargoing of such requests when action is taken based on them.) 

I'm not sure we're particularly fans of people making FOI requests in private are we? Though if such requests/response do occur we'd like them to be published via disclosure logs. 

We prefer proactive publication over FOI.

**Comment by garethrees** [comment]
From one of my [own requests](https://www.whatdotheyknow.com/request/traffic_incidents_between_heol_g#incoming-1068876):

> What we should have made clearer in our response is that we referred this as a 'business as usual' request

As far as I'm concerned I used my rights under FOI, so whatever they called it internally, the FOI Act still applies.

**Comment by FOIMonkey** [comment]
> As far as I'm concerned I used my rights under FOI, so whatever they called it internally, the FOI Act still applies.

That was a legit request! You've reminded me of a request I spotted recently when the authority said they wanted to deal with it outside of FOI in order to be able to give a faster and less formal response. Promptly is in the act for a reason, and nobody is obliging them to send responses on vellum!

**Comment by garethrees** [comment]
> That was a legit request!

I know! They did at least clarify that it was held elsewhere and I ended up getting what I was after.

> the authority said they wanted to deal with it outside of FOI in order to be able to give a faster and less formal response

Yeah, it seems like this is a similar case, and something the Climate programme were involved in had some similar notes when FOI was mentioned amongst some authority employees. There's a perception that it must be formal. (I'll post what I can about that here – just waiting on an OK that what I have is okay to share in public)

**Comment by garethrees** [comment]
> With regards to your request, we can handle it in an alternative way. If you agree, we can close down your Freedom Of Information request, then, if you respond directly to us at [[email address] with a personal email address for yourself we can arrange access via WeTransfer.
>
> – https://www.whatdotheyknow.com/request/mod_breach_video#incoming-2140442

"We can pretend we're not responding under FOI but in actual fact we are obliged to"

**Comment by zarino** [comment]
As you probably know, Climate Emergency UK are planning to use FOI to gather _some_ of the data in [next year’s Council Climate Action Scorecards](https://councilclimatescorecards.uk/methodology/). In case it’s useful, here are my notes from a consultation session they ran with council officers, where this “why use FOI, when you could just ask us for the answers” question came up:

1. Council climate officers claimed FOI was a waste of council time / resources. I’m not sure I really buy this (how much do they _really_ care about wastage at the council?) versus how much it’s just a publicly-acceptable cover for them to dislike FOI for another reason.

2. My hunch is that FOI is disruptive to council officers (I should re-read [our FOI & SAR research reports](https://research.mysociety.org/section/foi-and-sars-management), to see whether we’ve already proved or disproved this!) – but more than that, they feel they have to be “on best behaviour” when responding to FOIs, perhaps because FOIs carry an assumption of “investigation” or “dirt digging”. This might be why some officers mentioned a preference for responding “informally” via a direct email, rather than “formally” via the council’s FOI / information governance team. Do they feel “watched” when responding to FOIs? Does this limit what they’re willing to say?

3. ISTR that some officers mentioned that FOIs were too “formulaic”, and that their time and space to answer was limited (why?), so CEUK would be likely to receive shorter, more superficial, less useful responses to their questions, than if they’d “just emailed us”. Officers argued that, outside of the FOI process, they’d have space to fill in context behind the requested information, whereas inside the FOI framework, they’d only be able to provide the bare minimum response to satisfy the exact wording of the request. (Again, why?)

4. Finally, some officers implied that FOI questions might be answered by the “wrong” people at the council—perhaps by the information governance team themselves?—rather than the request finding its way to the climate officer for an informed response. And as a result, CEUK again would receive sub-optimal responses. Knowing how under-resourced and poorly connected council teams are, I can imagine this could indeed be the case in some circumstances!

**Comment by FOIMonkey** [comment]
Interesting. Thanks for sharing. 

My first thought is that legally, if I'm asking for recorded information, it's going to be an FOI/EIR request regardless. A lot of the "informal" responses are just non-compliant ones.

FOI/EIR might be seen as disruptive due to the fixed timescale for a response and the unpredictability (you don't know what will be asked for, or when). It's true that there are often several layers of approval that responses have to go through, so that may seem overly bureaucratic and time consuming.

On point 4, it's perfectly fine to make an FOI/EIR request directly to an individual council officer - any employee will do.

**Comment by WilliamWDTK** [comment]
I've started a [document for this blog post](https://docs.google.com/document/d/1tnQkspwLdhVJ7fwc4bnYVzyFfwoO2LI-QvAkmB_fsng/edit?usp=sharing).

**Comment by WilliamWDTK** [comment]
See also:

- #1095

**Comment by garethrees** [comment]
Another [example](https://www.whatdotheyknow.com/request/contaminated_land_investigations#incoming-2308417) of a body trying to avoid responding under FOI:

> The FOI method invokes a lot of different council staff… and slows down what… is usually a very fast process…  Please do approach me direct if you’ve contaminated-land enquiries.

**Comment by garethrees** [comment]
Also related is authorities saying they'll treat FOI requests as "normal business" / Business as Usual (BAU) / some other variation:

* https://www.whatdotheyknow.com/request/felling_licences_applications_an#incoming-2559269
* https://www.whatdotheyknow.com/request/traffic_incidents_between_heol_g#incoming-1068876

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
