### ISSUE TITLE
Blog post about why we don't think FOI should only be for "serious" requests

### ISSUE THREAD

**Issue by garethrees** [mysociety/whatdotheyknow-theme#1425]
There are many reasons people may want to make FOI requests.

There's the "serious" [Journalism, Campaigning, Academic Research](https://whatdotheyknow.com/pro), but also the everyday, like [ex-MOD vehicle history](https://www.whatdotheyknow.com/request/vehicle_history_request_for_land_3), or simply helping [those with mobility issues](https://twitter.com/WhatDoTheyKnow/status/1025388510474379264) have a slightly easier holiday.

> The day may come when we need to defend an FOI that is made because someone is curious and for no other reason. Hopefully, the Great British public will be on our side when we do. Most public libraries contain non-fiction books and books about ancient civilisations so hopefully the idea of the state paying to allow people to access interesting material is not completely alien to them. Any FOI system whereby requesters had to give a 'valid' reason would be far more bureaucratic than the one we have now.
>
> – @confirmordeny

When access to information laws – and public services more generally – are under threat, it's difficult to write about the more everyday uses and supporting those who are often [negatively perceived](https://github.com/mysociety/whatdotheyknow-theme/issues/1193) in society.

**Comment by confirmordeny** [comment]
There's certainly a category of requests that could be badged as 'personal benefit' rather than 'public interest' that I think can be defended. I thinking of requests for things like past exam papers, common interview questions, recipes and even the locations of council-owned fruit trees which is useful for foragers. 

See also: https://www.whatdotheyknow.com/request/139132/response/340993/attach/html/4/10850%2012599%2004%2012%2012%20TPO%20data.csv.txt.html
https://www.whatdotheyknow.com/request/chicken_fricasse_recipe_used_in#incoming-333842

**Comment by confirmordeny** [comment]
OK. I have created a document we can add ideas to here: https://docs.google.com/document/d/1UMsjT-TkyvdaPGcj77nsSDB-cxOoBgI-pnekwFFvP5Y/

**Comment by confirmordeny** [comment]
Similar in some ways to #1155

**Comment by RichardTaylor** [comment]
I agree with the concept here but don't think we should use the language of supporting requests which are not "serious" 

"No serious purpose" is one of the phrases used to describe/define a vexatious request. We want to be very clear that we do not support vexatious requests. 

Many of the requests mentioned might be made with personal or private interests in mind, but by making them via WhatDoTheyKnow the information becomes available to all and available for use by others. 

Even in the case of a request for a vehicle's service history - perhaps the example with the least public interest element - making the request in public demonstrates that others can obtain similar information, and there may well be analysis which could take place in the public interest, especially if the requests prompted a dataset release. 

Improving culture, artistic endeavours, and improving happiness all are serious purposes. 

The origami buses are a great example of a request with no significant public interest benefit, but with the potential to bring people enjoyment: 

https://twitter.com/WhatDoTheyKnow/status/1539363225413861379

As for

>past exam papers, common interview questions

I don't want to label requests for information, the release of which makes access to education, universities, and through that professions and productive roles in society as not-serious, or not of public benefit. I think these are likely to be some of  the most societally impactful requests we see getting made via WhatDoTheyKnow. While some requesters may have a personal interest I suspect some are pursuing a fairer society and some may have made an active decision to request the information in public, rather than privately. 

On a related point, we support disclosure logs. We want to see FOI responses published so anyone can use them. We want to see requests being made, and responses received, in public.  We don't want FOI requests/responses to just benefit specific individuals and organisations, we want them to benefit everyone.  A great example here would be those requests made by companies wanting to sell to public bodies, they have a private interest in finding out more about public bodies' needs, but by getting information release they make it available for others too.

**Comment by garethrees** [comment]
> don't think we should use the language of supporting requests which are not "serious"

Nor me, hence the quotes. I just wanted to ticket the general concept and that was the best phrasing I could come up with in the moment.

If you have a better phrasing in mind, please do suggest it!

The point is that not all requests are made by professional investigative journalists or researchers working on topics of national interest, but that doesn't make them less valuable.

**Comment by RichardTaylor** [comment]
"not of significant public interest" We're happy to support requests which are only of local, or hyperlocal interest, or where the benefits are just in making life a little more fun and interesting.

**Comment by RichardTaylor** [comment]
Requests where people are obtaining information to use to make novels, or computer games, more accurate and life-like could come under this category.

**Comment by WilliamWDTK** [comment]
"requests that aren't obviously important"?

**Comment by HelenWDTK** [comment]
Noted at https://wdtkwiki.mysociety.org/wiki/List_of_blog_ideas
