### ISSUE TITLE
Clarify policy on exam boards

### ISSUE THREAD

**Issue by confirmordeny** [mysociety/whatdotheyknow-theme#1466]
We have added quite a lot of exam boards to the site including many that are not subject to FOI:

https://www.whatdotheyknow.com/body/list/exam_board

We have stated publicly that we think exam boards should be subject to FOI:

https://twitter.com/WhatDoTheyKnow/status/1562860833319059456

We seem to be happy adding 11 plus exam boards:

https://github.com/mysociety/whatdotheyknow-theme/issues/1249

... and public exams
https://www.whatdotheyknow.com/body/aqa

... and bodies acting as exam boards for professional exams:
https://www.whatdotheyknow.com/body/cfa_uk

 Are there any limits on this?

**Comment by RichardTaylor** [comment]
See also:

https://www.whatdotheyknow.com/body/list/royal_college

>Are there any limits on this?

Are you thinking in terms of further professional/technical exams, music exams? 

Some companies will certify individuals as being competent users/resellers/operators of their products, presumably these generally shouldn't count as exam boards. 

I think the line is if they're fulfilling a state function, or a function which would otherwise need to be fulfilled by the state. 

This also prompts me to think about if we should list those who examine/inspect physical items rather than people.

**Comment by confirmordeny** [comment]
I have added some text to help clarify the policy:

_"We have stated publicly that we believe exam boards should be subject to FOI. [[1]](https://twitter.com/WhatDoTheyKnow/status/1562860833319059456) This extends to exam boards that run public exams such GCSEs and eleven-plus and to exams used to regulate access to a profession or trade."_


https://wdtkwiki.mysociety.org/wiki/Authorities_not_subject_to_FOI_policy#Exam_boards

**Comment by confirmordeny** [comment]
There are various other types of qualifications we could consider e.g. advanced driving, canoeing, dance, first aid, road safety, scuba diving, sign language, swimming, tour guide qualifications.
