### ISSUE TITLE
Consider responding to the consultation on FOI in Scotland

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1492]
https://www.parliament.scot/bills-and-laws/proposals-for-bills/proposed-freedom-of-information-scotland-bill

Deadline: 2 February 2023

**Comment by WilliamWDTK** [comment]
https://docs.google.com/document/d/16ubOk3F-o_1BQDu2MSHiSeVK4avogQI9LA_2vGhmF1s/edit?usp=sharing

(Perhaps a bit early…)

**Comment by ajparsons** [comment]
I've got a first draft of this in that document. 

In the interest of avoiding consultations being too much of a time sink this year I'm happy to ignore questions rather than develop opinions on everything. Left some comments where others might have stronger knowledge, but opinions all over are useful.

I'd generally like to use other orgs reponses to this to sharpen my opinions on questions like "how does extending to private providers work in practice", which I'm hopeful of having more time to develop in funded time later in the year rather than figure out at this point.

**Comment by WilliamWDTK** [comment]
Just to note that the preferred format for responses to this is a Microsoft Word document.

**Comment by ajparsons** [comment]
This has been submitted (in word document) - I'll close this ticket when I have the public version up (off sick atm, so prob in the next few weeks)

**Comment by garethrees** [comment]
Did we publish anything for this in the end?

**Comment by WilliamWDTK** [comment]
As far as I can tell, nothing has been published yet.

**Comment by confirmordeny** [comment]
The deadline has passed.
