### ISSUE TITLE
Better support mail stats for WDTK

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/whatdotheyknow-theme#1546]
### What's the Problem?
WhatDoTheyKnow receives a huge amount of email, from basic FOI questions through to complex GDPR cases.

Currently, it is one of the tasks of the Service Manager to perform the annual inbox audit. This has previously involved manually counting the number of messages that have been received using each label in the inbox during February.

There are several problems with this approach: 
- The survey has the potential to be skewed by one off events that happen during that month. 
- It doesn't enable us to spot or respond to new issues as they happen.
- Manual data gathering is less accurate and more time consuming than doing this automatically.

### What's the solution?
Automate the gathering of mail statistics that can be viewed and analysed on a real time basis.

### What have you done so far?

- I have written a script to pull the messageid, threadid, and label associated with each message into a spreadsheet. This runs once a day at midnight. 
- I have written and run a script to gather label usage and message count information for every thread that passed through the mailbox in 2021 and 2022.
- I have written a script that counts the number of messages in the inbox every hour.

I have used this data to produce three reports:

- Annual Inbox stats for 2022 - Which is what it says.
- "This Week In The Inbox" that pulls stats for the past 7 days, and compares them to the previous 7
- Inbox Monitor - This counts the number of threads in the inbox every hour, allowing us to spot if the level of mail is getting too much.

The data enables us to look at data for any combination of labels across any time period over the past two years.

### To do:
- [x] Document how the scripts work and where the data is stored on the wiki
- [x] Add links to the reports on the wiki
- [ ] Analyse the data and add the information to the correct ticket where tweaks to the contact form/help pages could reduce volume
- [x] Improve and expand the automatic reports

### To decide:
- What should we usefully track? One example I started with was to see what the top issues were that came in via the contact form last year because of the scope to better triage these.
-  Should we add some of this information to the transparency report?

**Comment by garethrees** [comment]
Would be good to be able to see messages sent/received on the graphs, as as this can be a good indication of how much work we need to put in relative to demand.

**Comment by garethrees** [comment]
Here are the key things we've been using:

* State of the inbox / [Inbox Monitor](https://lookerstudio.google.com/u/2/reporting/f838ecf8-b5ab-4113-8e67-3489910604c7/page/1jGBD): A short-term high level view of total number of threads and some other high-level stats, with weekly digest mails.
* [Last Week In The Inbox](https://lookerstudio.google.com/u/2/reporting/b8e321ea-3e34-4d91-a023-20bcd602c4c5/page/JueBD): A short-term look at the top threads by source, type, and change since last week.
* [Site content vs threads](https://github.com/mysociety/whatdotheyknow-theme/issues/1176#issuecomment-1514823751): Some annual calculations on requests vs thread ratio over a year, and graph of incoming/outgoing messages per month
* IRM Tracker - Cases becoming due: Weekly snapshot of IRM cases, with chart of inbox vs tracker caseload
* [2022 Inbox Statistics](https://lookerstudio.google.com/u/2/reporting/8550ed9b-4560-458a-9de8-8aa59822c77a/page/GcKBD): Lots in here, but here are the key themes:
  * Number of threads per label + annual change
  * Messages per period
  * Number of threads per source
  * Top labels by month
* [Inbox Analysis 2022](https://github.com/mysociety/whatdotheyknow-private/issues/219)
  * [Time to respond](https://lookerstudio.google.com/u/2/reporting/451856ce-078d-4315-8d41-f573f4d62cf2/page/SEeCD)
  * [Time to close/thread duration](https://lookerstudio.google.com/u/2/reporting/1bdf317d-45e9-424a-88ad-e1adf6ede5c5/page/SEeCD) 
  * [Thread lengths by label](https://lookerstudio.google.com/u/2/reporting/62bbc634-e04c-4ba3-b73b-fcfd0a3f6671/page/XV6LD)
* [Threads per month per label](https://lookerstudio.google.com/u/1/reporting/8d277cd9-315d-43b7-86c8-8b592ba08aec/page/BZYTD)

**Comment by garethrees** [comment]
> Analyse the data and add the information to the correct ticket where tweaks to the contact form/help pages could reduce volume

I think we can call this closed through https://github.com/mysociety/whatdotheyknow-private/issues/219.
