### ISSUE TITLE
Research / review funding of openaccess.transparency.org.uk with a view to the potential of seeking funding for similar projects from similar sources

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1555]

**Comment by RichardTaylor** [comment]
https://openaccess.transparency.org.uk/about.php 

states:

>The project is co-funded by the University of Oxford through a grant from the [Economic and Social Research Council (ESRC) Impact Acceleration Account](https://esrc.ukri.org/funding/funding-opportunities/impact-acceleration-accounts/), the [Joseph Rowntree Charitable Trust (JRCT)](https://www.jrct.org.uk/), The Amberstone Trust, [Omidyar Network](https://www.omidyar.com/), [Transparency International EU](https://transparency.eu/) (TI EU) and the [Hans and Julia Rausing Trust](https://www.juliahansrausingtrust.org/).

>The tool publishing the data is co-funded by the [Open Society Initiative for Europe (OSIFE)](http://www.opensocietyfoundations.org/about/programs/open-society-initiative-europe), with a contribution by the [King Baudouin Foundation (KBF)](http://www.kbs-frb.be/index.aspx?langtype=1033).

**Comment by RichardTaylor** [comment]
https://www.ukri.org/what-we-offer/supporting-innovation/innovation-epsrc/funding-for-impact/ states:

[Impact Acceleration Accounts (IAA)](https://www.ukri.org/what-we-offer/browse-our-areas-of-investment-and-support/epsrc-impact-acceleration-accounts/) are strategic awards provided to institutions to support knowledge exchange (KE) and impact from their EPSRC funded research.

Transparency International received a "core costs" grant from JRCT - £150,000 over 60 months (5 years).  [Reported in the JRCT 2020 annual report](https://www.jrct.org.uk/userfiles/Joseph%20Rowntree%20Charitable%20Trust%20Annual%20Report%202020.pdf).

**Comment by RichardTaylor** [comment]
In respect of an element of the project 

The project was funded by an ESRC IAA Kick-Start (1609-KICK-244) grant.

states

>The project was funded by an ESRC IAA Kick-Start (1609-KICK-244) grant.

This appears to be another reference to [Impact Acceleration Accounts (IAA)](https://www.ukri.org/what-we-offer/browse-our-areas-of-investment-and-support/epsrc-impact-acceleration-accounts/).

**Comment by garethrees** [comment]
Have passed this on

**Comment by ashapond** [comment]
Thanks for this research @RichardTaylor! Several of these funders are known to us, and some are new to me...

- We're currently receiving funding from JRCT, have previously received funding from Omidyar (they've since moved out of funding in the UK), and are hoping to receive funding in future from OSIFE.
- The Julia and Hans Rausing Trust is new to me, and it's interesting that they've funded this as it doesn't fit within their publicly stated priority areas of Health and Wellbeing, Welfare and Education, and Arts and Culture - but this can happen when a trustee has a particular interest in something! Like many trusts they don't accept unsolicited applications, so we'd need to find a connection with a staff member or trustee, but they're worth adding to the list.
- We're unfortunately not eligible for ESCR funding as we're not an 'independent research organisation' (you can see the criteria [here](https://www.ukri.org/wp-content/uploads/2022/06/UKRI-01062022-ELIGIBILITY-FOR-UKRI-RESEARCH-COUNCIL-FUNDING.pdf), which includes "a minimum of ten researchers with PhDs (or equivalent experience)").
