### ISSUE TITLE
Review our listing of Community Rehabilitation Companies (CRCs)

### ISSUE THREAD

**Issue by HelenWDTK** [mysociety/whatdotheyknow-theme#1594]
@garethrees has flagged up that these might now be defunct

The ones we list can be found here: https://www.whatdotheyknow.com/body/list/CRC

**Comment by mdeuk** [comment]
> these might now be defunct

Yep, I think they are. HMPPS [note in the target operating model](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1061047/MOJ7350_HMPPS_Probation_Reform_Programme_TOM_Accessible_English_LR.pdf#page=26) (p26):

_"We will transfer to the new unified model on 26th June 2021 following the end of CRC contracts (Day 1)."_

THis can be seen as confirmed, since the [quarterly absence statistics](https://www.gov.uk/government/statistics/hm-prison-and-probation-service-workforce-quarterly-december-2021/her-majestys-prison-and-probation-service-workforce-quarterly-december-2021) indicate:

_"This is an increase of 7,997 FTE (15.9%) staff in post since 31 December 2020 and a minimal change of 16 FTE (0.0%) since 30 September 2021. This includes over 7,000 staff transferred from the Private Sector Community Rehabilitation Companies (CRCs) in June 2021."_

We should look at marking these off as defunct. Some _may_ still have an existence, so we possibly can't do this en-masse.

**Comment by HelenWDTK** [comment]
The remaining 2 still exist as functioning companies, as per companies house.
