### ISSUE TITLE
Consider listing food/agriculture certifiers/control bodies/regulators

### ISSUE THREAD

**Issue by WilliamWDTK** [mysociety/whatdotheyknow-theme#1597]
As far as I'm aware, none of these organisations are formally subject. However, we could consider listing them as a form of campaigning. These organisations will often hold information relating to the environment which one could argue should come under the EIRs. I suspect they mostly don't receive significant public funding, though I have not investigated this in depth.

- [approved control bodies for organic food](https://www.gov.uk/guidance/organic-food-uk-approved-control-bodies): the Soil Association gets 1/15th of its funding from Government
- Inspectorates relating to PDO/PGI foods
- Animal welfare/production standards organisations

Some organisations may have a statutory basis, which would be another factor in support of listing them.

**Comment by RichardTaylor** [comment]
>[approved control bodies for organic food](https://www.gov.uk/guidance/organic-food-uk-approved-control-bodies)

We should list them on the basis they're doing a public, state, function. They are authorised to do something on behalf of the Government which otherwise the Government would, perhaps, do itsself. 


>   Inspectorates relating to PDO/PGI foods

These are inspectorates related to a protected designation of origin (PDO) or protected geographical indication (PGI) for food and drink.  

Do we also want to cover "[Traditional speciality guaranteed](https://en.wikipedia.org/wiki/Traditional_speciality_guaranteed)", it looks similar and there are three more classes of protected food and drink names at https://www.gov.uk/guidance/protected-geographical-food-and-drink-names-uk-gi-schemes 

If these are bodies with a role in law enforcement (albeit very specific laws) so I think we should list them. 

eg. in relation to Cornish Pasties we'd tag/list/add relevant notes to each of the inspection bodies listed in [the Cornish Pasty Specification](https://assets.publishing.service.gov.uk/media/5fd34f3dd3bf7f3059ef3cd2/pfn-cornish-pasty-pgi-pdf.pdf ) : Product Authentication Inspectorate Limited, SAI Global and Cornwall Council perhaps using eg. cornish_pasty_inspection_body

Would we need to go through the registers at 

https://www.gov.uk/protected-food-drink-names

and look at the specification documents and identify and add/tag the inspection bodies if we wanted a comprehensive list?


>    Animal welfare/production standards organisations

Would we list Marks and Spencers as the operator of their "M&S Select Farms standards" ? That doesn't feel right, as it's not a state / government / public function. 

There doesn't appear to be any state/legal backing for eg. the Red Tractor Assurance Scheme. 

Which bodies are being considered under this category and why would we consider them bodies with a public role which should be subject to FOI or similar access to information legislation?

**Comment by RichardTaylor** [comment]
Consider the lion mark on eggs

https://www.gov.uk/guidance/eggs-trade-regulations

Probably not, quite surprisingly

**Comment by confirmordeny** [comment]
now listed here: https://wdtkwiki.mysociety.org/wiki/Authority_suggestions
