### ISSUE TITLE
Follow the ICO's progress towards the production of a Data Protection and Journalism Code of Practice

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#1618]
It appears there has been some recent public debate on the draft proposals:

https://www.inpublishing.co.uk/articles/uk-editors-call-on-government-to-act-swiftly-on-ico-proposals-21493

It looks as if the latest consultation closed on 24 January 2022

https://ico.org.uk/about-the-ico/ico-and-stakeholder-consultations/ico-consultation-on-the-draft-journalism-code-of-practice/

* Consider if we should engage in the process of developing the code, and the debate on it. 
* We should see if our operations will be impacted by the code coming into force and respond accordingly.

The code may assist us in understanding when we can rely on the journalistic exemptions and derogations in data protection law.

**Comment by HelenWDTK** [comment]
Since this was opened, the ICO conducted and concluded a second consultation:

https://ico.org.uk/about-the-ico/ico-and-stakeholder-consultations/ico-second-consultation-on-the-draft-data-protection-and-journalism-code-of-practice/

And did a statutory review of data processing for journalism: https://ico.org.uk/about-the-ico/ico-and-stakeholder-consultations/ico-statutory-review-on-how-personal-data-is-processed-for-the-purposes-of-journalism/

I'm tracking ICO comms output more generally now, so we should be aware of future progress on this topic.
