### ISSUE TITLE
Make it clearer that which bodies  that we list are not subject to FOI/EIR

### ISSUE THREAD

**Issue by FOIMonkey** [mysociety/whatdotheyknow-theme#254]
At the moment the fact that a body is not subject to FOI is only included in the description on the authority page meaning there is a potential for confusion. Given that we say we list the bodies as a campaigning tool to get them made subject, it should be more obvious that this is what we have done.

**Comment by garethrees** [comment]
Got an example URL for a body that's not subject to FOI?

Are you suggesting something like a `[not subject to FOI]` suffix or similar?

**Comment by seurrep** [comment]
I added a request for NATS and only realised afterwards that it was not subject to the Freedom of Information Act. 

I can understand why such organisations might be listed, but since the primary purpose behind the whatdotheyknow website appears to be to make such requests it would not be unreasonable IMO for people to assume that any organisation listed is subject to the act and not properly read the description when they're searching for organisations.

I would suggest adding some text - something in bold perhaps, or slightly larger and/or a different colour? - on the form where the user actually makes their requests that says something along the lines of: 

'Please be aware that this organisation is not currently subject to the Freedom of Information Act 2000, and as a result of this any questions contained within your request may not be answered'.

Perhaps also include a link to writetothem.com & encourage them to write to their MP if they think this is wrong?

In addition put the part of the organisations description within any search results that says that they're not subject to the act in bold to make it more likely it will be read?

**Comment by FOIMonkey** [comment]
https://www.whatdotheyknow.com/body/national_air_traffic_services

At the moment the fact it is not subject blends into the rest of the description. The request page itself is better, with a banner in green at the top. At the very least we should explain why we have listed them, Adding a suffix could work (the same with EIR/INSPIRE only bodies)

**Comment by seurrep** [comment]
I would suggest green is the wrong colour. Red would be better as it would be more likely to get the attention of the user. I don't recall noticing it when making the request.

**Comment by garethrees** [comment]
Ah I've ticketed this (ish) in #237. I think that if a body is not subject to FOI then it deserves something even more bold than the notes field being highlighted.

**Comment by seurrep** [comment]
Green for me would be for information, not for warnings.

**Comment by garethrees** [comment]
Yeah, maybe a green highlight for general notes; yellow for special clauses (EIR) and red for if the body is not subject to FOI.

**Comment by lizconlan** [comment]
I think we can close this now that we have a note for `foi_no` authorities on the request page:

<img width="642" alt="screen shot 2018-08-16 at 10 39 14" src="https://user-images.githubusercontent.com/27760/44202362-a81aa780-a143-11e8-97a5-4152825e88a6.png">

(via mysociety/alaveteli#4499)

and a ticket to do something similar for the authority page itself mysociety/alaveteli#4814

(Feel free to reopen this if I've made a mistake!)
