### ISSUE TITLE
CTA in sidebar of WDTK requests, encouraging people to make requests to AskTheEU

### ISSUE THREAD

**Issue by zarino** [mysociety/whatdotheyknow-theme#313]
Essentially a banner advert for AskTheEU, in the sidebar of all WDTK requests, regardless of request state.

Can use the same wording as the homepage advert:

> **Looking for an EU Authority?**
> You can request *documents* directly from EU Institutions at our sister site <a href="http://www.asktheeu.org/">AskTheEU.org</a>.
> <a href="http://www.asktheeu.org/en/help/requesting">Find out more</a>

Part of https://github.com/mysociety/alaveteli-experiments/issues/50

Like https://github.com/mysociety/whatdotheyknow-theme/issues/297 except on the request pages rather than the homepage.

**Comment by garethrees** [comment]
I'd pop it under [next actions](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/request/_next_actions.html.erb) since the template override already exists so will be less of a faff to maintain.

**Comment by zarino** [comment]
A super quick solution would be to re-use the homepage banner in its entirety:

![screen shot 2016-05-09 at 16 28 44](https://cloud.githubusercontent.com/assets/739624/15118227/319e97ec-1603-11e6-9c11-56c3bcad423d.png)

@Gemmamysoc @garethrees: as a starter for 10, do you think that would fit the bill? Does the wording need changing? Are you ok with it appearing *above* the other action links?

**Comment by Gemmamysoc** [comment]
Hey @zarino - This looks like it's at the bottom of the request page, not the side bar? Or am I being silly?

**Comment by wrightmartin** [comment]
It's at the bottom, but it could be adapted at a small effort to go in the sidebar

**Comment by Gemmamysoc** [comment]
I just don't think many people will see it at the bottom of the page. What do you think @garethrees ?

We had a look to see how many people had been referred to AsktheEU from clicking on the links on WDTK's homepage - and it turns out that noone has clicked on them! We think that's because they're too far down the homepage.

**Comment by wrightmartin** [comment]
> We think that's because they're too far down the homepage

Could it be it's not useful to many people?

**Comment by zarino** [comment]
@wrightmartin beat me to it. I think we should stop talking, in isolation, about the position of an element on the page, because that's not the full story.

People will click this link if both of the following two conditions are met:

1. They see the link
2. They feel the link is relevant to them

There's a surefire way to fix number 1. Make a GIGANTIC big banner at the top of every page. Make it so that everybody's eyes have to pass over this thing. And keep it there for a few weeks. See whether you have any clicks. If you do, look at making the banner smaller, and see whether the number of clicks drops.

**Comment by garethrees** [comment]
Obligatory [life below 600px](http://iampaddy.com/lifebelow600/).

I have no real opinion on this, because as yet we don't know what works.

I'm happy to do whatever is easiest that makes an "Ad" happen somewhere on that page. I suggested the [next actions](https://github.com/mysociety/whatdotheyknow-theme/blob/master/lib/views/request/_next_actions.html.erb) section because we wouldn't need to override another view for it. Happy with @zarino's [suggestion](#issuecomment-217898612) too, as that means less work on the design end (although a little more maintenance our end).

At the end of the day, we can always move it if we don't see any results at the end of the sprint.

**Comment by Gemmamysoc** [comment]
Yeah, it's just to experiment really - to see if, like you say, 1) People actually see it and 2) That the links are actually relevant to people. 

I just want to make sure people actually see it as easily as possible :) Could we mention the EU referendum on the copy of the banner perhaps? Something like 'Looking for information from EU institutions ahead of the EU referendum in June? If so, use our sister site AskTheEU.org' Then copy could be tweaked after referendum? What do you think? I can get Myf to write better copy if we think this is a nice idea?

**Comment by Gemmamysoc** [comment]
Okay, after discussion with Gareth and Liz on standup - we think you should just go for your suggestion of this for now: https://cloud.githubusercontent.com/assets/739624/15118227/319e97ec-1603-11e6-9c11-56c3bcad423d.png  We can decide if we want a EU referendum-related banner in due course.

**Comment by Gemmamysoc** [comment]
Great, thanks!
