### ISSUE TITLE
Add unknown delivery status when we don't yet have logs for a message

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#373]
A user has queried why there's nothing where they're expecting a "delivered" notice and the green tick on a message they sent about eight hours ago. 

The request admin page text says the log excerpts shown on the request admin pages are updated hourly.

I see requests / messages sent yesterday have the "delivered" / green tick but not those sent today; and there are no mail logs on admin pages from messages sent so far today. 

* Are the logs being ingested hourly?

* Is showing nothing where the  "delivered" / green tick ought to be the intended behaviour or should there be a note telling users we don't have the delivery information yet?

**Comment by garethrees** [comment]
> Are the logs being ingested hourly?

Its pretty poor wording. We run the import script hourly, but we don't load in the most recent lines until the log has been rotated out of use, so in effect we ingest every 24 hours.

Just for reference, here's how that looks right now:

```sql
                filename                |         updated_at
----------------------------------------+----------------------------
 /var/log/all_servers_mail.log.20170213 | 2017-02-14 00:45:55.38006
 /var/log/all_servers_mail.log.20170212 | 2017-02-13 15:47:31.151873
 /var/log/all_servers_mail.log.20170211 | 2017-02-13 15:46:49.64017
 /var/log/all_servers_mail.log.20170210 | 2017-02-13 15:45:26.611625
 /var/log/exim4/exim-mainlog-20170213   | 2017-02-13 00:45:55.929759
 /var/log/exim4/exim-mainlog-20170212   | 2017-02-12 00:45:59.584749
 /var/log/exim4/exim-mainlog-20170211   | 2017-02-11 00:45:57.236444
 /var/log/exim4/exim-mainlog-20170210   | 2017-02-10 00:45:56.262323
 /var/log/exim4/exim-mainlog-20170209   | 2017-02-09 00:45:58.838455
 /var/log/exim4/exim-mainlog-20170208   | 2017-02-08 00:45:54.156415
 /var/log/exim4/exim-mainlog-20170207   | 2017-02-07 00:45:51.831309
 /var/log/exim4/exim-mainlog-20170206   | 2017-02-06 00:45:55.410529
 /var/log/exim4/exim-mainlog-20170205   | 2017-02-05 00:45:52.622351
 /var/log/exim4/exim-mainlog-20170204   | 2017-02-04 00:45:55.130828
 /var/log/exim4/exim-mainlog-20170203   | 2017-02-03 00:45:56.686382
 /var/log/exim4/exim-mainlog-20170202   | 2017-02-02 00:45:55.518101
 /var/log/exim4/exim-mainlog-20170201   | 2017-02-01 00:45:53.963867
 /var/log/exim4/exim-mainlog-20170131   | 2017-01-31 00:45:52.605328
 /var/log/exim4/exim-mainlog-20170130   | 2017-01-30 00:45:54.494547
 /var/log/exim4/exim-mainlog-20170129   | 2017-01-29 00:45:50.402746
```

Bit of a special case for the `all_servers_mail.log` as they were "new" on one of the hourly runs.

> Is showing nothing where the "delivered" / green tick ought to be the intended behaviour or should there be a note telling users we don't have the delivery information yet?

We can only show a "delivered" status when we have the logs. There's also a "sent" status, but usually delivery happens so quickly that you'd rarely catch it.

We [do handle an unknown status](https://github.com/mysociety/alaveteli/blob/develop/app/views/outgoing_messages/delivery_statuses/show.html.erb#L3-L8) for the text in the dropdown, so we should add similar handling [where we display the icon](https://github.com/mysociety/alaveteli/blob/7ae2247/app/views/request/_outgoing_correspondence.html.erb#L18-L24).

I've renamed the ticket that effect and marked it so that we look in to it next sprint. It's good to know people are noticing the feature at least :)

Notes to implementer:

I _think_ it would be worth creating a `MailServerLog::UnknownDeliveryStatus` with the same API, and returning a new instance of that if the map in `OutgoingMessage#delivery_status`  returns `nil`. I haven't checked whether the predicate methods all returning `false` would cause a problem.

```ruby
# app/models/outgoing_message.rb
  def delivery_status
    mail_server_logs.map(&:delivery_status).compact.last ||
      MailServerLog::UnknownDeliveryStatus.new
  end

# app/models/mail_server_log/unkown_delivery_status.rb
# -*- encoding : utf-8 -*-
class MailServerLog::UnkownDeliveryStatus
  include Comparable

  def initialize(status = nil)
    # NOOP: Argument maintained for API compatibility
  end

  def delivered?
    false
  end

  def sent?
    false
  end

  def failed?
    false
  end

  def simple
    :unknown
  end

  def humanize
    _("We don't have the delivery status of this message yet")
  end

  def <=>(other)
    to_sym <=> other.to_sym
  end

  def to_sym
    status
  end

  def to_s
    status.to_s
  end

  def inspect
    obj_id = "0x00%x" % (object_id << 1)
    %Q(#<#{self.class}:#{obj_id} @status=:#{ status }>)
  end
end
```
