### ISSUE TITLE
Alaveteli thinks mail delivery notification is from authority's MX but it's from mySociety's

### ISSUE THREAD

**Issue by kingqueen3065** [mysociety/whatdotheyknow-theme#392]
Ref https://www.whatdotheyknow.com/request/trainee_teacher_nqt_data_request_208#outgoing-640595
The PA evidently have MX issues. Ocelot has been unable to transfer the request email to the PA's MX. It's therefore returning "not yet delivered" messages until the email attempts eventually time out.
Alaveteli evidently considers Ocelot's delivery notifications to actually be from the PA's MX, because there's an erroneous green tick indicating successful delivery. Clicking it results in the message "This message has been delivered. We've received a delivery status notification from the mailserver belonging to the authority."
That's not correct though, as the log shows; said mails have just been bouncing around between Ocelot, Titan and Leopard.
![ss 2017-04-23 at 11 15 58](https://cloud.githubusercontent.com/assets/11923618/25317921/d9d238bc-287a-11e7-967c-d259de146c4b.png)
I suspect this incorrect categorisation is an unintended consequence of the email configuration change some months back.

**Comment by garethrees** [comment]
Problem here is that `mta_ids` is returning `["leopard"]` because the new syslog format has shifted the MTA ID from being the [fourth](https://github.com/mysociety/alaveteli/blob/develop/app/models/outgoing_message.rb#L448) element to the 9th.

I _think_ the solution here is to use a regexp to parse out the first exim MTA ID format string.
