### ISSUE TITLE
Bug in acknowledgement headers

### ISSUE THREAD

**Issue by mdeuk** [mysociety/whatdotheyknow-theme#409]
When WDTK is generating an acknowledgement header (sorry, I'm not sure of the name defined in the codebase), such as in response to following a request HTML markup is being incorrectly rendered in plain text.

An example is attached, but, in summary, the link to the request and the user's profile are both incorrectly rendered, producing a link which is not usable as it cannot be clicked on.

Steps to reproduce:

1. Open any request - my example is based on one of Jim Killock's series - https://www.whatdotheyknow.com/request/prevent_and_internet_filtering_p_91
2. Click the "Follow" option on the top RHS of the screen.
3. observe the resulting message

[
![img_0148](https://user-images.githubusercontent.com/249418/27688899-24d2e69e-5cd4-11e7-9b64-60ecb83abf7a.PNG)
](url)

**Comment by garethrees** [comment]
Hey @mdeuk,

We've already got a fix in place for this (https://github.com/mysociety/alaveteli/issues/3978) but there have been a few blockers in getting it released. It should be fixed in the next few days. 

Thanks for taking the time to put together a really clear bug report – always very appreciated! 🍰 👍
