### ISSUE TITLE
Create a whatdotheyknow.com/london page

### ISSUE THREAD

**Issue by markcridge** [mysociety/whatdotheyknow-theme#416]
Set up a London page on WhatDoTheyKnow at the domain london.whatdotheyknow.com which will provide a summary and access to all of the public bodies that you can submit an FOI request to in Greater London.

This should at a minimum be a structured and searchable listing page with topline stats displayed on total number of FOI requests made to each body.

Extending this further we could display results by Borough.

And further to this show more detailed statistics on success and response rates to each body, by Borough, by sector (such as all Local Authorities or all NHS Trusts etc).

This should be done in conjunction with the related ticket for a similar page on FixMyStreet.com.

This ticket will be essential within promotional activity for WhatDoTheyKnow in London and will act as a good testing ground for how this may be rolled out to other UK regions.

**Comment by garethrees** [comment]
What kind of timeline are we working to for this?

Can we do `whatdotheyknow.com/london` instead of a subdomain? Much easier (and more maintainable) from a tech perspective and would make it easier for reusers to apply the pattern.

We effectively already have this: https://www.whatdotheyknow.com/local/london – its "just" a matter of tagging up all the authorities.

**Comment by markcridge** [comment]
Yes, the /london sits well with /pro and other directories. 

It's much more the stats side that will need some design thinking and dev. On timings if we can identify some quick wins that would be great and assess what would be involved in a more substantial status display.

We could split of the tagging of authorities in London as a separate task perhaps.

**Comment by garethrees** [comment]
I've added a quick redirect so that when #417 is deployed, https://www.whatdotheyknow.com/london will be an accessible URL.

Currently we have 20 authorities tagged with `london`.

We have 629 authorities that have "london" in their name (e.g. "Beis Yaakov Primary School, London". Adding the `london` tag to these authorities would be pretty trivial, but sounds like it would be pretty overwhelming to a user to hit a page of 600+ authorities.

As an example of how we could make this easier to navigate, lots of the schools have a `school` tag. We could omit authorities tagged `london` _and_ `school` in the main results, and have a link through to those authorities in a separate list.

**Comment by markcridge** [comment]
As a starter would be good to tick off the obvious ones - so yes, please do mark all the schools as both 'school' and 'london'. If I can get an export of that then I can check this against the list of schools in London.

I'll also try to get a list of other bodies especially NHS and Police.

At a minimum would be good to ensure all London Boroughs are tagged as 'council' and 'london' as below;

City of London Corporation
City of Westminster
London Borough of Barking & Dagenham
London Borough of Barnet
London Borough of Bexley
London Borough of Brent
London Borough of Bromley
London Borough of Camden
London Borough of Croydon
London Borough of Ealing
London Borough of Enfield
London Borough of Hackney
London Borough of Hammersmith & Fulham
London Borough of Haringey
London Borough of Harrow
London Borough of Havering
London Borough of Hillingdon
London Borough of Hounslow
London Borough of Islington
London Borough of Lambeth
London Borough of Lewisham
London Borough of Merton
London Borough of Newham
London Borough of Redbridge
London Borough of Richmond upon Thames
London Borough of Southwark
London Borough of Sutton
London Borough of Tower Hamlets
London Borough of Waltham Forest
London Borough of Wandsworth
Royal Borough of Greenwich
Royal Borough of Kensington & Chelsea
Royal Borough of Kingston Upon Thames

**Comment by wrightmartin** [comment]
Here's a starter for ten.

![foi-near-me-london](https://user-images.githubusercontent.com/2292925/35322610-ccd38634-00e2-11e8-8a3f-15e9233aad52.png)

At it's core, it's just another version of the authority view, but I've made a few changes which serve to improve it from a local POV (I fully expect we can't do some of these without changes, if at all). I've also used it as an opportunity to try out some new things that might improve the authority information in WDTK as a whole.

### Header
The name of the area, with a nice photo. This would be specific to London and other major cities. With a more general area-based search we could show postcode or area name, with a map or a more generic photo header.

### Authority list

Authorities in the list show 'name', 'notes', 'number of requests', 'rating', 'request response time'.

#### Rating
The goal here is to give an at-a-glance measure of 'openness'. I'm not 100% sure how we can work this out in a fair way, but it's worth exploring?
How responsive they are, plus a measure of how many requests get completed/partial vs refused?

#### Request response time
Part of @markcridge's brief touched on making this kind of metric available - the goal is to set an expectation for the user - 'if I make a request how long might I wait for a reply?'


The list of authorities is likely to be large for most areas, so allowing sorting by different options and searching within the list is important to keep it useful.

### Local area overview
The goal of this section is to contextualise the area with the whole country, so the stats should be normalised. I'm not attached to any of the stats in particular, but thought it informative to show the figure, plus the comparison to other areas (green arrow up means higher than average, EG. London has 1727 authorities that are subject to FOI, this is higher than the average for other cities)

### Interesting requests
Rather than make this page all about the authorities alone, I thought we could show requests to local authorities that have generated interest in some way, be that referrals, annotations or traffic. I think without this the page was very authority-centric.

### National authorities
This is to acknowledge that national authorities have local impact. I'm not sure how we decide which ones to show here, but thought it was important.

@zarino I'm interested in your famed utilitarian critique on this :)

**Comment by zarino** [comment]
> @zarino I'm interested in your famed utilitarian critique on this :)

I. Love. It.

Star rating for authorities is a super interesting idea. Will be tricky to calculate fairly, but if we _can_ do it, it’s a nice way to congratulate authorities that serve the public well, while not being _too_ defamatory about authorities that drag their heels.

And the "typically resolves requests within…" stat for each authority is lovely. We have it for a few bodies on FMS (eg: Oxfordshire – "reports in this category are usually responded to within X days") and it’s a nice expectation-management feature. Also gives an indication of how snowed-under authorities are.

I wonder whether you could display a list of (mutually exclusive) tags along the top, like "councils / schools / hospitals / police / …" – it would both advertise the scope of the data we hold ("Look at all these things you use every day! I wonder whether your school is in here? Or your local hospital?") as well as making the list easier to navigate and compare within.

Once you’ve got authorities tagged (eg: "schools") it might be an opportunity to compare a given authority’s performance (eg: response time) against the average or the distribution for that tag. Like "[This school] responds to more requests than the average school in London", or "[This school] resolves requests quicker than average among schools in London", or "[This school] is in the top 10% of most responsive schools in London" …?

I didn’t understand the green arrows in the "Local area overview" box. To me, green and red arrows mean "change over time" (eg: stock price tickers), not "difference compared to something else". Why not just display _both_ the local value and the national value smaller and greyer underneath it?

**Comment by wrightmartin** [comment]
>  wonder whether you could display a list of (mutually exclusive) tags along the top, like "councils / schools / hospitals / police / …"

Yes! A fine idea

> I didn’t understand the green arrows in the "Local area overview" box. To me, green and red arrows mean "change over time" (eg: stock price tickers), not "difference compared to something else". Why not just display both the local value and the national value smaller and greyer underneath it?

Yeah, they mean changes over time to me too, now you've said it. 

> Once you’ve got authorities tagged (eg: "schools") it might be an opportunity to compare a given authority’s performance (eg: response time) against the average or the distribution for that tag. Like "[This school] responds to more requests than the average school in London", or "[This school] resolves requests quicker than average among schools in London", or "[This school] is in the top 10% of most responsive schools in London" …?

I like this but maybe it's for the 'authority details page' itself rather than this screen

**Comment by wrightmartin** [comment]
Here's a couple of experiments around revealing the categories of the authorities.

I think whatever approach we choose we need to be selective about which categories we show – showing all of them at once is quite laborious for the viewer. As you can see below

![version 2](https://user-images.githubusercontent.com/2292925/35688463-2192f4a2-0769-11e8-8452-b7591cc18b73.png)

I've solved this by showing the first five, then having a link to reveal all (I assume this will be some javascript reveal code).

![version 2a](https://user-images.githubusercontent.com/2292925/35688462-2179a92a-0769-11e8-88c2-f12280b21aee.png)

Another complexity to consider is that the categories span multiple levels - so the interface must allow some way of navigating the tree, which I've explored below

![screen shot 2018-02-01 at 16 09 57](https://user-images.githubusercontent.com/2292925/35689010-6afaa120-076a-11e8-8806-df53590b7fa6.png)

Here I think that displaying each category would be mutually exclusive - clicking one top level would close all the others before revealing its children.

Unfortunately this means my original idea (and per @zarino's suggestion) of showing the categories across the top is a lot more complex than first glance. How would the tree traversal work here? Does clicking each category explode into it's children, or does it show a new page 'London -> Transport & infrastructure'
![version 3 copy](https://user-images.githubusercontent.com/2292925/35688460-2152a3c0-0769-11e8-8388-c9a6dd0d8d20.png)

**Comment by garethrees** [comment]
[Notes](https://docs.google.com/document/d/1Ew04rLs4aNmUSOMx5bX0PixGjPXV_I_du7zorBZ0O2I/edit#heading=h.eci5nmeit7xm) from @wrightmartin's chat with @markcridge about this. Also drafting some user stories there to get a better idea of why someone might hit `/london` and what they're trying to achieve when they get there, vs a general authority search.

**Comment by garethrees** [comment]
This often comes to mind from the notes doc above, so pasting it here for easy reference.

![Screenshot 2019-05-21 at 17 27 44](https://user-images.githubusercontent.com/282788/58113593-c7bc9000-7bed-11e9-883d-3faf4ba289bc.png)
