### ISSUE TITLE
Show more information on costs and funding

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#434]
Currently there is only a single sentence at:
https://www.whatdotheyknow.com/help/credits#funding

Expanding what we publicly say about how the site is funded would:

* Show we operate transparently ourselves.
* Explain why donations are valued/required.
* Give context to why a chargeable "pro" service is being developed.

Options:
* Expanding the existing help page section.
* A new help-page section.
* A special page on how the service is funded.

Ideas:
* a chart showing the gap between the income generated by the site and what it costs to run.
* evaluating the donations in time put in by volunteers.
* encouraging donations from the funding page.
* setting a justified periodic donations target.

Even if some of the information was estimated this could be a useful thing to have. 
The aspiration for a self-sustaining site/service could be mentioned along with content on current funding.

**Comment by RichardTaylor** [comment]
Following on from this ticket saying we should be transparent over our funding, here's a proposal for an update to the about page. 

Currently 

https://www.whatdotheyknow.com/help/about#who

says just:

>The site was initially funded by the JRSST Charitable Trust. 
>If you like what we’re doing, then you can make a donation. 


Draft new text:
>The site was initially funded by the [JRSST Charitable Trust](http://www.mysociety.org/2006/12/06/funding-for-freedom-of-information/). The most significant supporters of the site since have been the volunteer administrators who have given their time to run the site on a day to day basis ([you can join them!](https://www.whatdotheyknow.com/help/volunteers)).  

>[Google’s Digital News Innovation Fund](https://newsinitiative.withgoogle.com/dnifund/) supported the development of [Alaveteli Professional](https://www.whatdotheyknow.com/pro), and unrestricted [support from a number of funders](https://www.mysociety.org/about/funding/) ensured that mySociety has been able to continue paying their developers to work on the project. The [Adessium Foundation]( https://www.adessium.org/) is currently funding part-time administrative support to assist the volunteers, and is also supporting the development of the [Alaveteli](https://www.whatdotheyknow.com/help/alaveteli) software for use on WhatDoTheyKnow and elsewhere.  

>If you like what we’re doing, or would like to fund us to help us do more, then [please do get in touch](https://www.whatdotheyknow.com/help/contact).  You can also [make a donation](https://www.mysociety.org/donate/). 


Some text taken from "Funding to date" section at:
https://www.mysociety.org/2018/10/19/ensuring-whatdotheyknow-is-around-for-the-next-half-a-million-requests/

**Comment by RichardTaylor** [comment]
I may have overstepped what I'm supposed to do with the labels, but having offered what I suspect is an uncontentious proposal to improve the text on the about page I wanted to flag acting on this for reconsideration.

**Comment by mdeuk** [comment]
I'm in heated agreement with this modification - it certainly improves the clarity of who is funding what.

> > [Google’s Digital News Innovation Fund](https://newsinitiative.withgoogle.com/dnifund/) supported the development of [Alaveteli Professional](https://www.whatdotheyknow.com/pro), and unrestricted [support from a number of funders](https://www.mysociety.org/about/funding/) ensured that mySociety has been able to continue paying their developers to work on the project. The [Adessium Foundation](https://www.adessium.org/) is currently funding part-time administrative support to assist the volunteers, and is also supporting the development of the [Alaveteli](https://www.whatdotheyknow.com/help/alaveteli) software for use on WhatDoTheyKnow and elsewhere.
> 

Could we perhaps change 'elsewhere' to something more descriptive - e.g. "for use on WhatDoTheyKnow and other right-to-know services around the world". That feels slightly flowery, but, it does emphasise the global aspect here, which seems important in the context.

**Comment by garethrees** [comment]
Here's what Adessium are supporting https://www.mysociety.org/2019/05/29/alaveteli-pro-a-chance-to-increase-transparency-across-europe/

**Comment by MattK1234** [comment]
Just noting that I agree we should do this, however following the discussion on the catch up call, it appears there have been some changes to mySociety funding that would need to be reflected in the above.

**Comment by RichardTaylor** [comment]
It appears this would be useful to others running, or planning to run, Alavetli based services. 

The proposed draft text above is, as has been noted, no longer up-to-date. 

Following discussion on a recent catch-up call we could link to the mySociety annual report on the Charity Commission website, this doesn't provide a WhatDoTheyKnow specific breakdown though, and is provided in an image format, so it's not really ideal.

**Comment by garethrees** [comment]
> perhaps [if true] say that WhatDoTheyKnow is funded from mySociety’s unrestricted funds.

It's partially true.

Sometimes we get [specific](https://www.mysociety.org/2020/07/24/whatdotheyknow-projects/) [funding](https://www.mysociety.org/2020/09/29/challenging-refusals-upholding-the-right-to-information/) for a project on WDTK, lots of the time a wider project funding which [partially](https://www.mysociety.org/2019/05/29/alaveteli-pro-a-chance-to-increase-transparency-across-europe/) includes WDTK, and sometimes we get funding which doesn't directly contribute to WDTK, but many of the features developed are either derived from our experience running WDTK or derived from international install feedback but will benefit WDTK.

Some of the unrestricted funds are contributed by WDTK (donations and pro subscriptions). We also run an [FOI Works](https://www.societyworks.org/services/foi/) instance – based on our extensive FOI experience – which earns SocietyWorks some money which then gets donated back into mySociety's unrestricted funds.

It's more complicated than "WDTK is funded by X".

**Comment by RichardTaylor** [comment]
I've expanded to the scope of this in the title to include costs as well as funding. Funding is only part of the story - how the income/resources gets spent/used is the other.  To meet the aims of this ticket both sides of the equation are needed.

**Comment by RichardTaylor** [comment]
>Explain why donations are valued/required.

Including donations in terms of time/expertise.

**Comment by RichardTaylor** [comment]
It might also be useful to have clarity on what mySociety funds vs what is left to volunteers. 

More specifically what mySociety is, and is not, prepared to fund from various sources. 

There's also a question of what the aspirations / strategies are in terms of funding the service and the role of volunteers.

**Comment by RichardTaylor** [comment]
One reason for doing this is to provide prospective, new and current volunteers context for their volunteering.

**Comment by RichardTaylor** [comment]
Take care not to present the financial situation in such a way that it unduly works against the aim of [presenting the service as something likely to be around for the foreseeable future and so a service which can be relied upon for serious endeavours. ](https://github.com/mysociety/whatdotheyknow-theme/issues/934)

**Comment by garethrees** [comment]
I'm not sure what their organisational structure is (LLC, but maybe seems like there's community involvement), but MetaFilter have been going through some opening up of operating context (via https://www.gyford.com/phil/writing/2022/11/06/weeknotes/#s4)

<blockquote>
<p>On MetaTalk there’s <a href="https://metatalk.metafilter.com/26170/-Metafilter-Wants-You--The-Fundraising-Post">the fundraising post</a>, <a href="https://metatalk.metafilter.com/26172/MeFi-Site-Update-October-26th">a site update</a>, <a href="https://metatalk.metafilter.com/26173/MeFi-Posts-for-Sale">an opportunity to pay for posts on a topic you like</a>, <a href="https://metatalk.metafilter.com/26176/Metafilter-Wants-You-Fundraiser-Week-1-update">a fundraising update</a>, <a href="https://metatalk.metafilter.com/26177/MetaFilter-Financial-Update-November-2022">a financial update</a>, <a href="https://metatalk.metafilter.com/26178/Advertising-a-text-based-website-in-2023">a search for ideas about how to advertise the site</a>, <a href="https://metatalk.metafilter.com/26179/AskMe-Black-Friday-Fundraiser">a Black Friday fundraiser</a>, <a href="https://metatalk.metafilter.com/26180/After-the-Fire-Metafilter-Should-Consider-Replacing-Itself">a proposal for spin-off sites</a>, <a href="https://metatalk.metafilter.com/26181/What-is-MetaFilter-worth-to-you">a question about the value of the site to users</a>, <a href="https://metatalk.metafilter.com/26185/Approaches-to-reduce-AWS-hosting-costs">a post about how to reduce the site’s $3,000/month AWS costs</a>, and then <a href="https://metatalk.metafilter.com/26183/Mefi-Mastodon-server">the idea of creating a MeFi Mastodon instance</a>. That’s all in the past two weeks. Plus the ongoing subreddit discussion of all that. It’s probably too much and I shouldn’t read any and yet…</p>
</blockquote>

Seems like they're in a bit of trouble rather than just wanting to be more open by default.

**Comment by HelenWDTK** [comment]
Closing as complete via addition of extra information about funding
