### ISSUE TITLE
Adwords landing pages

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#442]
This is something we've considered before because it allows us to hold the user's hand to an extent, by explaining a bit about what the site is and how to use it, rather than throwing them straight onto a page where they might not understand exactly what they were seeing.

There's now an extra reason to do this, which is that our ads pointing to the Department of Health's authority page keep getting banned. After a bit of back and forth I've learned that it's the mention of a specific drug in [one of the requests](https://www.whatdotheyknow.com/request/current_plans_regarding_liothyro) currently showing on the page that is triggering this.

Obviously we can't do what Google advise, which is to remove that request, and equally obviously, we can't control what requests might appear at any time in the future. So until Google get a bit smarter about why they ban ads, I think landing pages are our answer.

**Comment by garethrees** [comment]
Great examples on the climate action site:

![Screenshot 2021-11-02 at 15 23 57](https://user-images.githubusercontent.com/282788/139877109-cf91c35f-319f-436e-a74b-f70f3191e934.png)

![Screenshot 2021-11-02 at 15 24 07](https://user-images.githubusercontent.com/282788/139877082-93d6d1a5-f66c-4998-92f8-7f84d59a7950.png)

* Love the motivating language
* Love the strong call to actions
* Love the quick action guides
* Love the "path to action" ("Your superhero journey starts here")

**Comment by garethrees** [comment]
FragDenStaat has a really nice [climate information helpdesk](https://fragdenstaat.de/aktionen/klima-helpdesk/).

![fragdenstaat de_aktionen_klima-helpdesk_](https://user-images.githubusercontent.com/282788/154232429-8d5e568f-c51e-4844-85c2-a61f7224adc8.png)

**Comment by garethrees** [comment]
Should add `/foi` (or `/freedom-of-information`), `/eir` (or `/environmental-information-regulations `). We could:

* briefly explain why it's good, and the basics of the mechanics
* Maybe add a bit of a process diagram around requests, responses, and escalation routes
* pull in relevant case studies https://github.com/mysociety/alaveteli/issues/6589
* Link to refusal advice
* pull in featured / cited requests

Similar to https://github.com/mysociety/alaveteli/issues/6788. 

Could also add a `/climate` landing page as a context-specific use of both acts. Cover similar ground, but instead of explaining the legislation, explain how each legislation can be used in the context of requesting climate info.

**Comment by garethrees** [comment]
Linking to https://github.com/mysociety/orgsites/issues/1000 which suggests _removing_ some from mysociety.org due to poor performance (other services, but worth considering).

**Comment by garethrees** [comment]
Just noting that I followed up on this recently. The gist is that conceptually they're worthwhile because of the extra hand holding you can do. At the time we could only use google ads on a single domain, which is why they all ended up on mySociety.org. The ones that work less well are likely more down to not meeting user needs very well (and haven't really been reviewed for a long time), so they still work in principle, and it’s more down to us to garden them to get the most from them.
