### ISSUE TITLE
More information about embargoed requests on the help pages

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#473]
We could add a sentence encouraging people to contact the team if they're aware of a request which is embargoed which they think should now be published. Perhaps the Pro team could pass on such requests to the Pro user in question?

See also #454

**Comment by garethrees** [comment]
I'll leave this issue open for discussion, but I'm not sure about the proposed "implementation" to this problem.

Here are some thoughts:

* We try to avoid viewing specific requests as much as possible, because customers are expecting a reasonable level of privacy. We obviously need to view contents for admin purposes, but I think digging through requests is definitely on the more questionable side of what a customer would expect.
* The story may refer to only a small portion of the documents, which may be being used for further stories.
* I think this is _fairly_ unlikely to come up, except for big, national news stories. I think when it does come up though, there's a good public interest in publishing.

This is definitely a tricky balance to find.

**Comment by garethrees** [comment]
Just pasting some text I've been using to reply to information officers that may be useful when drafting some of this:

> For various reasons, some requests may not appear immediately on the WhatDoTheyKnow website.
> 
> * Our search indexing takes some time before requests are indexed for public visibility.
> * Admins may hide requests from other users if they contain personal information in the request.
> * Requests may be made through our new WhatDoTheyKnow Pro [1] service, which allows journalists, activists and campaigners to keep requests and responses private while they work on their investigation.
> 
> We do state that "Please note that in some cases publication of requests and responses will be delayed.” in the footer of the request emails we send.
> 
> Our decision if to publish, or not, a correspondence thread does not impact a public body's duties to respond.
> 
> I can confirm that the email addresses are valid addresses to reply to.

**Comment by garethrees** [comment]
Closing in favour of https://github.com/mysociety/whatdotheyknow-theme/issues/454 as they're basically tackling the same thing.

**Comment by garethrees** [comment]
https://github.com/mysociety/whatdotheyknow-theme/pull/586 has been merged and so https://www.whatdotheyknow.com/help/pro includes some more general info on embargoes.

**Comment by garethrees** [comment]
Oh, I meant to close this one! https://github.com/mysociety/whatdotheyknow-theme/issues/473#issuecomment-510434517
