### ISSUE TITLE
Add page to internal Wiki about Facebook

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#601]
Didn't even know we had a Facebook page...

Found the link to https://www.facebook.com/whatdotheyknowcom/ at https://www.whatdotheyknow.com/help/about

We should add a page to the Wiki about this.

*Who manages / posts to it.
*What do we use it for
*Can volunteers access it (similar to Twitter)?

**Comment by MyfanwyNixon** [comment]
At the moment it's mainly 'managed' by me, but like most mySociety Facebook pages, the community aspect is not really nurtured due to a lack of time. So in effect it is basically a place to post when we have relevant blog posts or other FOI-related news to disseminate. It's pretty much the same messaging as we put out via Twitter.

Perhaps worth noting that as with all our FB pages, the ability for users to DM us via this page has been turned off: after a few years we could state with certainty that a relevant message has never come through this channel.

If any WDTK volunteers were interested in putting more time into the page I'd be happy to add them as admin. My own preference would be for an arrangement as with twitter where I know the volunteers are mainly tending to it, but I have access to post etc.

**Comment by MattK1234** [comment]
Closing this now as I have created (and added content to!) https://wdtkwiki.mysociety.org/wiki/Facebook
