### ISSUE TITLE
Consider adding gas and electricity licence holders

### ISSUE THREAD

**Issue by MattK1234** [mysociety/whatdotheyknow-theme#653]
In terms of energy companies, the decision notice here appears to relate to E.ON (FER0678164 [2]).

There is some very interesting legalese in this case as the ICO have considered E.ON's status both as former holder of an electricity generation licence and that of a supplier of gas and electricity (para 40-49 of the DN). This definition is perhaps helpful as it pushes beyond our more traditional interpretation of the Fish Legal case (e.g. where we've gone on to list the National Grid and Cadent).

Ofgem have a list of gas and electricity license holders which we could use as a starter for ten in expanding our listings:
List of all electricity licensees with registered or service addresses - https://www.ofgem.gov.uk/publications-and-updates/all-electricity-licensees-addresses
List of all gas licensees with registered or service addresses - https://www.ofgem.gov.uk/publications-and-updates/list-all-gas-licensees-registered-or-service-addresses

... we will, perhaps, however want to try and refine these listings (for example, to group subsidiaries of the 'big six' into more manageable chunks).

Naturally, of course, it's likely that the companies will be considering whether or not to appeal the ICO decision (the DNs are relatively 'fresh', and, E.ON has already been before the Upper Tribunal on a technical point regarding the same [3]); however, I don't think this should necessarily influence any action on our part - listing bodies in line with our usual policy seems to be a reasonable action.

[2] https://ico.org.uk/media/action-weve-taken/decision-notices/2020/2617169/fer0678164.pdf
[3] https://assets.publishing.service.gov.uk/media/5ce29e9d40f0b627e35ea361/GIA_1862_2018-00.pdf

**Comment by mdeuk** [comment]
Thanks for the reminder to work on this @MattK1234… I had forgotten to file a ticket for the energy companies.

### Electricity Distribution Network Operators

I've added a new category for this body type as '[dno](https://www.whatdotheyknow.com/body/list/dno)', under the heading 'Environment and agriculture'…

Based on Ofgem's [data](https://www.ofgem.gov.uk/electricity/distribution-networks/gb-electricity-distribution-network), there are 14 DNOs in GB, owned by **six** different groups. I think it's probably okay if we list a parent body and reference the individual entities, rather than create an individual entry for each DNO.

We already had [Western Power Distribution](https://www.whatdotheyknow.com/body/western_power_distribution) (88033) listed, so I've tidied up this listing and included some new tags.

I have added:

- [Electricity North West Limited](https://www.whatdotheyknow.com/body/electricity_north_west_limited) (92627)
- [Northern Powergrid](https://www.whatdotheyknow.com/body/northern_powergrid) (92628)
- [Scottish and Southern Energy Networks](https://www.whatdotheyknow.com/body/ssen) (92626)
- [Scottish Power Energy Networks](https://www.whatdotheyknow.com/body/scottish_power_energy_networks) (92624)
- [UK Power Networks (Operations) Limited](https://www.whatdotheyknow.com/body/uk_power_networks_operations_limited) (92625)

### Gas Distribution Networks

I've added a new category for this body type as '[gdn](https://www.whatdotheyknow.com/body/list/gdn)', under the heading 'Environment and agriculture'…

Based on Ofgem's [data](https://www.ofgem.gov.uk/gas/distribution-networks/gb-gas-distribution-network), there are eight GDNs in GB, operated by **four** companies.

We already had [Northern Gas Networks](https://www.whatdotheyknow.com/body/northern_gas_networks_limited) (58195) listed, so I've tidied up this listing and included some new tags.

I have added the following new bodies, with appropriate tags:

- [Cadent Gas Limited](https://www.whatdotheyknow.com/body/cadent) (92621)
- [Scotia Gas Networks Limited (SGN)](https://www.whatdotheyknow.com/body/sgn) (92622)
- [Wales & West Utilities Limited](https://www.whatdotheyknow.com/body/wales_west_utilities_limited) (92623)

**Comment by MattK1234** [comment]
Great additions!

I think we can close this now as they've been added.

**Comment by mdeuk** [comment]
Just to note, 

It would appear that E.On are appealing the ICO's decision - case ref **EA/2020/0089**

https://www.gov.uk/government/publications/information-rights-register-of-tribunal-cases/information-tribunal-register-of-current-cases
