### ISSUE TITLE
Promote free month of Pro for articles based on requests on Pro pricing page

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#719]
Currently 

https://www.whatdotheyknow.com/pro/pricing

doesn't mention one of the key exciting and potentially impactful elements of the pro pricing structure - the free month for FOI requests which make the news,  which is mentioned at

https://www.mysociety.org/2018/03/05/sending-multiple-foi-requests-the-whatdotheyknow-pro-batch-feature/ 

that article says:

>Send us links to your published stories and we’ll throw in an extra month of WhatDoTheyKnow Pro for free. 

This is a great incentive to make good use of WhatDoTheyKnow / WhatDoTheyKnow pro

Perhaps the offer could be extended to two months free where the request/batch is publicly available and cited and linked from the article?

The offer as currently phrased only rewards users who publish articles citing their own requests, perhaps this scheme, or some other reward scheme, could be extended to

i/ Journalists, researchers etc. who cite others' requests
ii/ Users whose requests are picked and cited by others

**Comment by RichardTaylor** [comment]
Inspiration could be taken from another service provider:

>You can earn credits that cover the cost of paid Notion plans — and even making them free for certain periods of time. You can earn credit by using Notion features. Below is a full guide to how this works 

https://www.notion.so/Earn-credit-7f39e3701b3f482ba313e60461fabee8

**Comment by WilliamWDTK** [comment]
@garethrees, is this still policy?

**Comment by garethrees** [comment]
Let's say no, not at the moment.

We added a dashboard announcement back in 2018, and maybe did some specific promotion. It's just sat there since then so its never really been a "policy" as such. We also never really put much thought in to the specific mechanics (i.e. is 1 month per link; 1 per "batch", something else?) and the whether there's a limit to the offer.

We didn't get a huge amount – if any – of links from it (and it was probably before we had the citations feature). We don't currently have a process of routinely checking citations added and then applying any related discounts (which I think would be quite a faff to monitor, calculate the discount, and then get it applied). 

We do have a specific promotion around [citations applied to batch requests](https://www.mysociety.org/2024/08/01/tell-us-how-youve-used-batch-requests-get-free-pro-credit/) that would be good to promote. 

Other than that, discounts for citations are discretionary but not a routine policy, process or expectation. I've deleted the announcement.

I would like to revisit this as links to wider impact are really important for us.
