### ISSUE TITLE
Enable administrators to prompt a cache update

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#737]
Administrators often need to remove material from the site promptly, including legally problematic material, personal information etc. 

While updates are instant for those logged in, apparently due to caching updates are not instant for non-logged in users. 

This causes problems including:
* We continue to publish problematic material for longer than necessary, potentially increasing both legal risk and harm. 
* Administrators have to either wait for the cache to update before responding to someone to say the issue has been resolved, or respond to say, rather unsatisfactorily, that the change has been made but may take time to take effect due to caching. 

This ticket is proposing a web interface to whatever developers do to refresh the cache for particular pages.  

It would probably ideal if any such system automatically dealt with the Welsh translation version of a page as well as the English to prevent two requests having to be made, or to prevent one from being overlooked. 

Related: https://github.com/mysociety/whatdotheyknow-theme/issues/588

**Comment by mdeuk** [comment]
I'm adding the label 'reduce-admin' because this has the potential to reduce the administrative burden of dealing with the 'waiting time' when handling certain problematic cases where administrative action is necessary. 

It's not clear whether or not we should file this upstream, or if the cacheing in this particular instance is a feature of the WDTK infrastructure, rather than Alaveteli "out of the box".

**Comment by garethrees** [comment]
> This ticket is proposing a web interface to whatever developers do to refresh the cache for particular pages.

We did once have some interaction between Alaveteli and Varnish, but that proved unreliable so it was removed (https://github.com/mysociety/alaveteli/pull/4252).

> It's not clear whether or not we should file this upstream, or if the cacheing in this particular instance is a feature of the WDTK infrastructure, rather than Alaveteli "out of the box".

I'm going to close this as the underlying cause is https://github.com/mysociety/alaveteli/issues/1475. With a well-designed cache system, items would be correctly marked as stale at appropriate times and then a fresh copy should be fetched. Creating a web interface would take just as much work.
