### ISSUE TITLE
Review citations pointing to WhatDoTheyKnow on Wikipedia and write a blog about this use of the service

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#823]
Inspired by 

https://twitter.com/confirmordeny/status/145850250198913024

**Comment by mdeuk** [comment]
Adding 'impact' label since, undoubtedly, this is a positive effect of having FOI requests on WDTK visible to everyone.

There's definitely areas where Wikipedia and Wikidata cross over with our own datasets and where we can also learn from their experiences.

**Comment by RichardTaylor** [comment]
Links from public body pages on Wikipedia are covered by 

https://www.mysociety.org/2020/05/13/whatdotheyknow-in-wikidata/

If we tagged requests and bodies on WDTK appropriately we could link to the relevant Wikipedia articles from body and request pages on WhatDoTheyKnow.

**Comment by RichardTaylor** [comment]
Links from public body pages on Wikipedia are covered by 

https://www.mysociety.org/2020/05/13/whatdotheyknow-in-wikidata/

If we tagged requests and bodies on WDTK appropriately we could link to the relevant Wikipedia articles from body and request pages on WhatDoTheyKnow.

**Comment by MyfanwyNixon** [comment]
No doubt there are clever ways to do this with code, but I was curious. Wikipedia's search covers citations so it's relatively easy to compile a list of 20 of the 'most relevant' roughly according to their sorting of results (the below are a mix of results for 'WhatDoTheyKnow' and 'What Do They Know' with gaps).

Another approach would be to look at Analytics and see which Wikipedia pages send us the most actual users.

- [British Forces Gibraltar](https://en.wikipedia.org/wiki/British_Forces_Gibraltar) links to [this request](https://www.whatdotheyknow.com/request/745642/response/1782914/attach/3/202105%20FOI2021%2003836%20Zacchi.pdf?cookie_passthrough=1) and others
- [Trunk Roads in Wales](https://en.wikipedia.org/wiki/Trunk_roads_in_Wales) links to [this request](https://www.whatdotheyknow.com/request/263607/response/648506/attach/4/Appendix%20A%20Welsh%20Government%20List%20of%20Trunk%20Roads.pdf)
- [HMS Eaglet (shore establishment)](https://en.wikipedia.org/wiki/HMS_Eaglet_(shore_establishment)) links to [this request](https://www.whatdotheyknow.com/request/669180/response/1596389/attach/2/FOI%202020%2006471Final%20response.pdf?cookie_passthrough=1) and another
- [Intelligence Corps](https://en.wikipedia.org/wiki/Intelligence_Corps_(United_Kingdom)) links to [this request](https://www.whatdotheyknow.com/request/664382/response/1596315/attach/3/20200706%20FOI05506%20Arbeely%20Response%20Letter%20ArmySec.pdf?cookie_passthrough=1) and others
- [Shadwell DLR](https://en.wikipedia.org/wiki/Shadwell_DLR_station) - and all the DLR stations in fact - link to [this request](https://www.whatdotheyknow.com/request/passenger_numbers_5#incoming-989461)
- [Cheshire County Council](https://en.wikipedia.org/wiki/Cheshire_County_Council) links to [this defunct body](https://www.whatdotheyknow.com/body/cheshire_county_council) - as proof of its districts
- [Cornwall County Council](https://en.wikipedia.org/wiki/Cornwall_County_Council) links to [this defunct body](https://www.whatdotheyknow.com/body/carrick_district_council)
- [Manchester Pride](https://en.wikipedia.org/wiki/Manchester_Pride) links to [this request](https://www.whatdotheyknow.com/request/manchester_pride_event_2017#incoming-1028403)
- [Chester Cathedral Constables](https://en.wikipedia.org/wiki/Chester_Cathedral_Constables) links to [this request](https://www.whatdotheyknow.com/request/531483/response/1272931/attach/html/5/FOI%2010710%20q1.docx.html)
- [British Rail Class 499](https://en.wikipedia.org/wiki/British_Rail_Class_499) links to [this request](https://www.whatdotheyknow.com/request/325139/response/803040/attach/3/LU%20Rolling%20Stock%20Unit%20formation%20asset%20list%202016.pdf)
- [Denefield School](https://en.wikipedia.org/wiki/Denefield_School) links to [this request](https://www.whatdotheyknow.com/request/headteachers_at_denefield#incoming-772006)
- [John Ritblat](https://en.wikipedia.org/wiki/John_Ritblat) links to [this request](https://www.whatdotheyknow.com/request/summary_letter_to_the_crown_esta#incoming-1259708)
- [Scotstoun Stadium](https://en.wikipedia.org/wiki/Scotstoun_Stadium) links to [this request](https://www.whatdotheyknow.com/request/occupant_capacity_of_scotsoun_st)
- [Broadband](https://en.wikipedia.org/wiki/Broadband) links to [this request](https://www.whatdotheyknow.com/request/378588/response/924461/attach/3/296020%20Reply.pdf)
- [Banc y Betws](https://en.wikipedia.org/wiki/Banc_y_Betws) (and other scheduled monuments across Wales) links to [this request](https://www.whatdotheyknow.com/request/15714/response/38315/attach/html/2/SAMs%20by%20UA.xls.html)
- [Flag Institute](https://en.wikipedia.org/wiki/Flag_Institute) (subject of the original tweet that inspired this ticket) links to [this request](https://www.whatdotheyknow.com/request/393927/response/959318/attach/5/ADR%20Part%2011%20Flying%20Flags%20in%20UK.pdf)
- [List of Lakes of Wales](https://en.wikipedia.org/wiki/List_of_lakes_of_Wales) links to [this request](https://www.whatdotheyknow.com/request/future_capacity_to_supply)
- [Television licensing in the UK](https://en.wikipedia.org/wiki/Television_licensing_in_the_United_Kingdom) links to [this response](https://www.whatdotheyknow.com/request/copy_of_ask_help_script#incoming-571034) and several others
- [160th Welsh Brigade](https://en.wikipedia.org/wiki/160th_(Welsh)_Brigade) links to[ this request](https://www.whatdotheyknow.com/request/596571/response/1430033/attach/3/20190911%20FOI09576%20Lai%20Response%20Letter%20ArmySec.pdf?cookie_passthrough=1) and others
- [Surrey Police](https://en.wikipedia.org/wiki/Surrey_Police) links to [this request](https://www.whatdotheyknow.com/request/cross_reference_of_police_office) and others
- [Bramcote Hills Sport and Community College](https://en.wikipedia.org/wiki/Bramcote_Hills_Sport_and_Community_College) links to [this request](https://www.whatdotheyknow.com/request/details_on_closure_of_bramcote_h#incoming-70666) and others


Next step would be to judge which have the most human interest, which I'll do (but anyone should feel free to note any they think are interesting).

**Comment by MyfanwyNixon** [comment]
Google Analytics is potentially more interesting actually - because it shows which links actually bring people to the site, and these do look to have more of a human interest angle. However, numbers are small.

**Desktop Wikipedia** -  in the last year, 61 pages brought visits to WDTK and the maximum number of visits a single citation has brought is 9. 

1. [Border Five](https://en.wikipedia.org/wiki/Border_Five)
2. [Police ranks of the UK](https://en.wikipedia.org/wiki/Police_ranks_of_the_United_Kingdom) 
3. [Special Constabulary](https://en.wikipedia.org/wiki/Special_Constabulary)
4. [Unique Reference Number](https://en.wikipedia.org/wiki/Unique_Reference_Number)
5. [Five Country Conference](https://en.wikipedia.org/wiki/Five_Country_Conference)
6. [Karol Sikora](https://en.wikipedia.org/wiki/Karol_Sikora)
7. [TV licensing in the UK](https://en.wikipedia.org/wiki/Television_licensing_in_the_United_Kingdom)
8. [736 Naval Air Squadron](https://en.wikipedia.org/wiki/736_Naval_Air_Squadron)
9. [Leamside Line](https://en.wikipedia.org/wiki/Leamside_line)
10. [State-owned enterprises of the UK](https://en.wikipedia.org/wiki/State-owned_enterprises_of_the_United_Kingdom)

**Mobile Wikipedia** (numbers are even smaller; most of these have only 1 visit) - 

1. [Special Constabulary](https://en.wikipedia.org/wiki/Special_Constabulary)
2. [College of Arms](https://en.m.wikipedia.org/wiki/College_of_Arms)
3. [Farnworth and Kearsely First](https://en.m.wikipedia.org/wiki/Farnworth_and_Kearsley_First)
4. [Government of the British Indian Ocean Territory](https://en.m.wikipedia.org/wiki/Government_of_the_British_Indian_Ocean_Territory)
5. [King's College London](https://en.m.wikipedia.org/wiki/King's_College_London)
6. [TV licensing in the UK](https://en.wikipedia.org/wiki/Television_licensing_in_the_United_Kingdom)
7. [TV detector van](https://en.m.wikipedia.org/wiki/TV_detector_van)

(Anecdotally, I've noticed quite a few links to WDTK from Reddit whenever TV detector vans come up; it's clearly providing a useful fact checker on that topic).

Interestingly there are also a few referrals from other wikipedias:  China, Poland, Japan, Italy, Germany, France.
In these cases I am guessing (but am not sure) visitors start on their own language's Wikipedia homepage but end up on an English language page which then links to us. In these cases Analytics only records their entry point into the site that referred them, it would seem.

**Comment by garethrees** [comment]
This is great. We should clearly make the point that our publishing of _authoritative_ information helps build the world's "[largest and most-read reference work in history](https://en.wikipedia.org/wiki/Wikipedia)" – we play a part in combating misinformation and providing accurate reference material.

There might be some interesting comparison to [this bit of research](https://twitter.com/swardley/status/1394935595500245000/photo/1) about how the "next generation" of work is orchestrated – "leaderless" and "non-hierarchical swarming". This is exactly what's happened here, and [c4 & c5 of Making Things Work](https://necsi.edu/making-things-work) has some good insight into this. Basically, hierarchical structures limit the complexity of problem that can be solved. That's the typical "old way" of doing things – gov publish what they want to publish as the tip of the hierarchy. FOI (and in particular, our publication) allows this distributed use of information to better form the basis of our "new generation" knowledge (wiki).

This is probably all a bit too detailed for what we want to do here, but I was just thinking out loud and wanted to note it down for future reference.

**Comment by MyfanwyNixon** [comment]
Here's a draft post. https://docs.google.com/document/d/1SdhndpVOgjgbB8VHdy-xAnHzIaAT1g6DTknpnifJd3U/edit#

**Comment by MyfanwyNixon** [comment]
Now live at https://www.mysociety.org/2021/06/22/whatdotheyknow-and-the-wikipedia-citation/
