### ISSUE TITLE
Add a photo to body pages illustrating the area they cover

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/whatdotheyknow-theme#880]
Images could come from www.geograph.org.uk or Wikipedia. 

This might be particularly appropriate for parish council level bodies. 

See also: 

* https://github.com/mysociety/whatdotheyknow-theme/issues/818

which is another idea for showing an image giving users an indication of the area covered by a body. 

and 

* https://github.com/mysociety/alaveteli/issues/6172

**Comment by RichardTaylor** [comment]
Example:

https://www.whatdotheyknow.com/body/isle_of_wight_council

**Comment by zarino** [comment]
My worry with a ticket like this is whether you completely automate the process of selecting images (which means you could end up with [images like this](https://www.geograph.org.uk/photo/3886244) which contribute absolutely nothing to a user’s understanding of the public authority or its role) or you take on the responsibility of curating images (which means now you have an extra thing to spend precious volunteer time on, or to ignite user support flame wars over).

What does an image _actually add_ to the UX of requesting information? Other than making the page "prettier"?

I can imagine that the official _logo_ of the public authority might help us lend legitimacy to the authority’s page, and maybe might also help users disambiguate similarly-named authorities (because they’re familiar with the logo of the authority they’re attempting to contact).

I’m finding it hard to imagine a similar justification for more generic images. But maybe that’s just me.

**Comment by WilliamWDTK** [comment]
> I can imagine that the official _logo_ of the public authority might help us lend legitimacy to the authority’s page, and maybe might also help users disambiguate similarly-named authorities (because they’re familiar with the logo of the authority they’re attempting to contact).

The problem with the logo is that it might further confuse users into thinking they are contacting the body directly/privately, since this already happens as the site is.

**Comment by RichardTaylor** [comment]
>What does an image actually add to the UX of requesting information? Other than making the page "prettier"?

I think "prettier" is sufficient justification. Why do people put pictures up in their homes?  There's some positive response at https://github.com/mysociety/alaveteli/issues/6586#issuecomment-1183466649 and https://twitter.com/mockduck/status/1547545639927664642 

As for improving functionality I think back to discussions mySociety had about getting professional design input to its websites at all. The websites functioned, but the idea was they'd be attractive to a wider group of people if they looked nice, and looked contemporary.  There was also a suggestion that for some people appearance is linked to credibility. It might be easier to maintain, and build, a reputation for a service which looks, at least conventional, but ideally attractive. We want to be running websites people trust and feel comfortable using. 

It may be that if we show a user a picture of their local hospital, or a landmark in their local area, they will get a greater sense that the service is relevant to them than they would from a text-only page. 

>I can imagine that the official logo of the public authority might help us lend legitimacy to the authority’s page, and maybe might also help users disambiguate similarly-named authorities (because they’re familiar with the logo of the authority they’re attempting to contact).

I don't think disambiguation is a major reason for adding images. I think an image of an area help with disambiguation purpose though. If there's an image of a prominent building in a town/city on the relevant council's page on WhatDoTheyKnow it will help users confirm (or not) that they're on the right page.

**Comment by FOIMonkey** [comment]
> It may be that if we show a user a picture of their local hospital, or a landmark in their local area, they will get a greater sense that the service is relevant to them than they would from a text-only page.

This. It's all about making a connection.

**Comment by RichardTaylor** [comment]
Linking to the Alaveteli ticket for a feature enabling adding such images "properly" via a dedicated feature in the software: https://github.com/mysociety/alaveteli/issues/7160
