### ISSUE TITLE
Updating Data Breach Process on Wiki

### ISSUE THREAD

**Issue by sallytay** [mysociety/whatdotheyknow-theme#937]
We should develop that process to standardise our threshold for assessing, either involving scoring or having some boxes in the assessment which if ticked prompt a report to the ICO

Proposed template / process for making decisions on serious (or not) Data Breaches. 

To consider while assess data breaches

== Number of individuals affected ==
(To note generally lesser is an indicator of lower risk)

== Seriousness of PII released   ==

== Fairness of releasing PII ==

== Impact on individuals rights  ==

==  Existing publication of PII == 

To work on format of this and then add to the WDTK Wiki Data Breach Page

Sally

**Comment by mdeuk** [comment]
> We should develop that process to standardise our threshold for assessing, either involving scoring or having some boxes in the assessment which if ticked prompt a report to the ICO
> 
> Proposed template / process for making decisions on serious (or not) Data Breaches.
> 

It strikes me that this risk matrix could probably be done on a Google Form, so we've got an auditable copy of it on file when working on a request.

I quite liked the initial draft @garethrees shared in this respect, but I can see a benefit to capturing additional data surrounding interpretation of the data itself.

It's been quite some time since I last did risk modelling, but let me have a think! 🙂

**Comment by garethrees** [comment]
> I quite liked the initial draft @garethrees shared in this respect

Just linking to https://github.com/mysociety/whatdotheyknow-theme/issues/1378.

**Comment by HelenWDTK** [comment]
This has been overtaken by the new serious data breach policy and associated guidance. Closing as complete.
