### ISSUE TITLE
Add Help section on anonymisation of requests

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/whatdotheyknow-theme#994]
At the last quarterly data protection review meeting, I took the action
>Talk to volunteers and then write help page section on WDTK on requests from users to anonymise their accounts (@sallytay can help with this too).

I note that this section is currently under 'Your rights to erasure':

>Names If you have made requests for information via our site and are considering asking us to remove your name, please do take a moment to reflect and reconsider. Typically Freedom of Information requests made via our service form a positive part of an individual’s online footprint; a public record of civic activism is something to be proud of.

> That said, we understand that there can be good reasons why you may want us to remove your name and will make our best efforts to do so if you ask us to. Similarly, we may also remove other personal information. Note that if your name has been released as part of an authority’s response, we may not be able to remove it easily, however we will of course consider formal “right to be forgotten” / “right of erasure” requests and remove material if we are unable to justify continuing to hold and process it.

If people would like to note any further information on this ticket I'll be happy to work up some draft amendments to this copy (or a new section if it seems more apt).

**Comment by sallytay** [comment]
As this is already on available on site on the privacy page, which is listed as one of the help pages, if we were to make this an individual help page, this would need to be looked at along with other help page improvement suggestions rather than something we'd do as a standalone improvement.  

I think the text above itself is fine, perhaps just the positioning of it on the site that we need to think about when reviewing the general content of the help pages.
